### ISSUE TITLE
Demux and Index Before Creating Jobs - Batch Processing

### ISSUE THREAD

**Issue by almanteka** [Revan654/staxrip#10]
previous versions of StaxRip included the option to demux and index before creating jobs for batch processing, any chance that this option will return? i constantly used the option because i process a considerable amount of files of different kind, including containers, languages, bitrates and sizes! without this option i can't demux and index all files at once and then, adjust some parameters for the individual files. i created my own templates, but sometimes a file or two need adjustments within that profile and is imposible without that option! thanks for all your hard work and for keeping alive this great app!
![staxrip](https://user-images.githubusercontent.com/42816936/44809978-4e33cc00-ab9e-11e8-9250-679ef4b057a0.jpg)

**Comment by Revan654** [comment]
1. Do you recall what version it was included in?

I do believe it was removed when the full Automation process was added in.

Manually Demux still exist if you need to call on it ad Advance -> Demux.

**Comment by almanteka** [comment]
thanks for your reply! the last time i saw the option was at v1.6. the option in Advance -> Demux only works with one file, making tedious to process batch files. thanks for your interest!

**Comment by Revan654** [comment]
All reference of that code has been removed,It looks like it kept breaking the process or it would skip a file completely if the source filter didn't like the codec.

You can still do it through a power script or Event Commands.

PowerScript Discussion: https://github.com/stax76/staxrip/issues/200****

**Comment by almanteka** [comment]
thanks! in reality, i only need for the batch option to demux and create the jobs and NOT begin to encode immediately. that way i can verify every job and then process all the files using the start button on the jobs window. suggestions are welcome! thanks!

**Comment by almanteka** [comment]
thanks! as a workaround, i updated the apps on v1.6 and continued to using that version! sorry to hear about the code been removed. i liked that option because of the demuxing of the batch files prior to creating the jobs. maybe i don't confront any problems using it 'cause the source filter is automatic on my templates. i know that will not work for other users! thanks for all your help, and for the hard work involved keeping satxrip updated and alive!

**Comment by Revan654** [comment]
Like I said you can use a basic script that will auto index the file for you when you load a file. Script engine is built into StaxRip.

**Comment by almanteka** [comment]
thanks! hope someone can provide an example of an auto indexing script to use with newer versions of staxrip! don't know anything about scripting! that's why i love staxrip, everything automatic and all included onto one program! thanks for your suggestions and help! and thanks in advance for anyone that can suggest an auto index script!

**Comment by almanteka** [comment]
looking for a suggestion, i read the topic for StaxRip support thread on the Doom9's forums and stax76 suggested to add a batch file to the windows sendto menu. the batch file:

> @echo off
for %%i in (%*) do (
    "D:\Apps\StaxRip.exe" -loadTemplate:"template name" %%i -addjob -exit
)

i tested this and works perfectly, now i'm testing how to integrate this to staxrip directly!
