### ISSUE TITLE
[Question] How to run 2.0.2.4 - x64 without error

### ISSUE THREAD

**Issue by samkatakouzinos** [Revan654/staxrip#100]
**Describe the bug or Issue**
Starting StaxRip from their unpacked locations gives an error of not finding the Versions.txt file under the Apps folder from where they run.

**Step To Reproduce the Problem**
1. Go to unpacked 'Staxrip.2.0.2.4.x64' folder
1. Go to either v4.7 / v4.8 folder.
1. Start StaxRip.exe
1. Main window opens.
1. Error message opens.

**Screenshots**
If possible, add screenshots to help explain your problem.

![StaxRip_2019-06-28_18-28-07](https://user-images.githubusercontent.com/1305871/60328964-b3309c00-99d2-11e9-8fb9-9961b966f698.png)

![StaxRip_2019-06-28_18-28-40](https://user-images.githubusercontent.com/1305871/60328973-b9267d00-99d2-11e9-9903-67b47ecf448d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1809 17763.592
- StaxRip Version: 2.0.2.4 - x64
- Post your Logs, There Tell contain Allot of Information that Could Help.

**Question**
Am I meant to choose one version and copy the exe and config file to the folder above?

**Comment by Revan654** [comment]
Addressed In Project Page.
