### ISSUE TITLE
Some little Bugs with version 2.0.2.4

### ISSUE THREAD

**Issue by darkman1983** [Revan654/staxrip#101]
There is an path issue on first start of this version, it wants the App-Folder to be in the 4.8 or 4.7 executable folder (I simply temp fixed it by creating a symlink with mklink @Win10).
And the Icon on the StaxRip Window is the Standard icon from IDE...

**Comment by Revan654** [comment]
Stax76 already fixed the Icon, The other was that I wasn't aware ffms2 package was Changed and Split across the two FrameServers. This creates the problem, It's looking for folder & File in the wrong directory.  Which is a easy fix.
