### ISSUE TITLE
Path length problem

### ISSUE THREAD

**Issue by barbatrukko** [Revan654/staxrip#103]
**Describe the bug or Issue**

When the file path is too long the system goes into error

**Add The Proper Label**

**Step To Reproduce the Problem**

1. I open satxrip
2. I drag and drop file to convert into "source" text filed (a mkv h264 in this case)
3. Software automatically start to create temp folder and index file.....
4. software return error "DIrectoryNotFoundException 2.0.2.0"
5. if i move file to another location on desktop o simply i rename some intermediate directory 
to shorten the path, all works fine

a path of 133 char + filename of 77 char go on error, but if I shorten path to 67 and same filename all works fine...

**Screenshots**
![PathProblem](https://user-images.githubusercontent.com/23135977/61997520-e8e4a580-b0a2-11e9-8014-87228a9d60ad.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1903
- Version 2020

**Comment by Revan654** [comment]
You need to enable LongPath, This is Only Supported on Windows 10 with NTFS harddrives. Below that you can not surpass the 255 character length. There nothing that can be done since this is tied directly to the OS.

You also have to take into account the TempFiles that get added to the Path.

**Comment by barbatrukko** [comment]
> You need to enable LongPath, This is Only Supported on Windows 10 with NTFS harddrives. Below that you can not surpass the 255 character length. There nothing that can be done since this is tied directly to the OS.

Hi, where/how I can enable LongPath?
 
> You also have to take into account the TempFiles that get added to the Path.

I know.

**Comment by Revan654** [comment]
> 
> 
> > You need to enable LongPath, This is Only Supported on Windows 10 with NTFS harddrives. Below that you can not surpass the 255 character length. There nothing that can be done since this is tied directly to the OS.
> 
> Hi, where/how I can enable LongPath?
> 
> > You also have to take into account the TempFiles that get added to the Path.
> 
> I know.

It's in the registry(It's should be in Local_Machine, not 100% Sure where off the top of my head), I know there also option somewhere in the settings not 100% where it's at, it's a bit hidden.

Also if you install python(normal Edition as Admin), It will ask you at the end if you want to Enable Long Path.

**Comment by fmohican** [comment]
Hit the Windows key, type gpedit.msc and press Enter.
Navigate to Local Computer Policy > Computer Configuration > Administrative Templates > System > Filesystem > NTFS.
Double click the Enable NTFS long paths option and enable it.


If you’re using a version of Windows that does not provide access to Group Policy, you can edit the registry instead.

Hit the Windows key, type regedit and press Enter.
Navigate to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\ CurrentVersion\Group Policy Objects\ {48981759-12F2-42A6-A048-028B3973495F} Machine\System\CurrentControlSet\Policies
Select the LongPathsEnabled key, or create it as a DWORD (32-bit) value if it does not exist.
Set the value to 1 and close the Registry Editor.

**Comment by Bradum** [comment]
I really appreciate you making this tool for us, but it's such a pain having to move around and rename files just to re-encode them. 

I found this in the Windows documentation:
"The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters. This type of path is composed of components separated by backslashes, each up to the value returned in the lpMaximumComponentLength parameter of the GetVolumeInformation function (this value is commonly 255 characters). To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path"."

Is there a reason the unicode version can't be used? I've never had an issue opening longer filepaths with any other software.
