### ISSUE TITLE
Staxrip 2.0.2.4 MASSIVE delay from indexing to actually opening the file. 

### ISSUE THREAD

**Issue by jessielw** [Revan654/staxrip#104]
I am using the latest stable build of Staxrip. I use it for 4k HDR encodes. I always do manual source selection. I'm using FFvideosource for the 10-bit pipeline with avisynth. As soon as the program is done indexing the file, everything minimizes. It appears to be doing something in the background because if I wait 5 - 10 minutes it finally opens up in the program where I am able to use the UI and make my selections. 

This DOES not happen in version  2.0.2.0 at all. It's basically instant from index to UI using the exact same sources/files/settings/filter. 

I am not sure what has changed from that version to this one. However, I tried both framework .exe's that are included. Reinstalled avisynth etc and it's the same problem regardless. 

On top of that error above^^^
If I'm already encoding a 4k video, open another instance of StaxRip to do some work/add a job. Sometimes it will fully crash my computer. This did not happen on the previous version of staxrip neither. Unfortunately I didn't get any logs etc.

**Comment by Revan654** [comment]
I know Stax76 made some changes to the code from what I previous had, Not 100% sure what all the changes were. Plus ffms2 Indexer is not in the best shape right now, It has some issues(Which is beyond my control). At times the indexer can run twice for some reason.

**Comment by jessielw** [comment]
I could be wrong. But with avisynth to encode 4k hdr with 10 bit pipe ffms2 is the best option? 

Also I went back and tested the older version as stated above again to make sure and the file indexed and opened up immediately  

I'd be down to test stuff out if you make changes.
