### ISSUE TITLE
Error Indexing using ffmsindex (2.0.2.4)

### ISSUE THREAD

**Issue by YinnVI** [Revan654/staxrip#105]
> 
> -------------------------- System Environment --------------------------
> 
> StaxRip    : 2.0.2.4
> Windows    : Windows 10 Pro 1903
> Language   : Indonesian (Indonesia)
> CPU        : Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
> GPU        : Intel(R) HD Graphics 610, NVIDIA GeForce GTX 1050
> Resolution : 1920 x 1080
> DPI        : 96
> 
> ------------------------ MediaInfo Source File ------------------------
> 
> D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv
> 
> General
> Complete name            : D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv
> Format                   : Matroska
> Format version           : Version 4
> File size                : 3.13 GiB
> Duration                 : 39 min 9 s
> Overall bit rate mode    : Variable
> Overall bit rate         : 11.4 Mb/s
> Encoded date             : UTC 2019-08-01 17:18:59
> Writing application      : mkvmerge v8.6.1 ('Flying') 32bit
> Writing library          : libebml v1.3.3 + libmatroska v1.4.4
> 
> Video
> ID                       : 1
> Format                   : AVC
> Format/Info              : Advanced Video Codec
> Format profile           : High@L4.1
> Format settings          : CABAC / 5 Ref Frames
> Format, CABAC            : Yes
> Format, Reference frames : 5 frames
> Codec ID                 : V_MPEG4/ISO/AVC
> Duration                 : 39 min 9 s
> Width                    : 1 920 pixels
> Height                   : 816 pixels
> Display aspect ratio     : 2.35:1
> Frame rate mode          : Constant
> Frame rate               : 23.976 (24000/1001) FPS
> Color space              : YUV
> Chroma subsampling       : 4:2:0
> Bit depth                : 8 bits
> Scan type                : Progressive
> Writing library          : x264 core 157 r2935 545de2f
> Default                  : Yes
> Forced                   : No
> 
> Audio
> ID                       : 2
> Format                   : FLAC
> Format/Info              : Free Lossless Audio Codec
> Codec ID                 : A_FLAC
> Duration                 : 39 min 9 s
> Bit rate mode            : Variable
> Channel(s)               : 2 channels
> Channel layout           : L R
> Sampling rate            : 48.0 kHz
> Bit depth                : 24 bits
> Compression mode         : Lossless
> Title                    : Main 2.0
> Writing library          : libFLAC 20080709 (UTC 2008-07-09)
> Language                 : Japanese
> Default                  : Yes
> Forced                   : Yes
> 
> ------------------ Demux MKV using mkvextract 35.0.0 ------------------
> 
> D:\Staxrip.2.0.2.4.x64\v4.8\Apps\Support\MKVToolNix\mkvextract.exe "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv" tracks 1:"D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] G ID1 Japanese.flac" --ui-language en
> 
> Extracting track 1 with the CodecID 'A_FLAC' to the file 'D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] G ID1 Japanese.flac'. Container format: raw data
> 
> Start:    15.14.02
> End:      15.14.49
> Duration: 00:00:47
> 
> General
> Complete name         : D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] G ID1 Japanese.flac
> Format                : FLAC
> Format/Info           : Free Lossless Audio Codec
> File size             : 376 MiB
> Duration              : 39 min 9 s
> Overall bit rate mode : Variable
> Overall bit rate      : 1 344 kb/s
> 
> Audio
> Format                : FLAC
> Format/Info           : Free Lossless Audio Codec
> Duration              : 39 min 9 s
> Bit rate mode         : Variable
> Bit rate              : 1 344 kb/s
> Channel(s)            : 2 channels
> Channel layout        : L R
> Sampling rate         : 48.0 kHz
> Bit depth             : 24 bits
> Compression mode      : Lossless
> Stream size           : 376 MiB (100%)
> Writing library       : libFLAC 20080709 (UTC 2008-07-09)
> 
> -------------------- Error Indexing using ffmsindex --------------------
> 
> Indexing using ffmsindex failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 
> 
> ----------------------- Indexing using ffmsindex -----------------------
> 
> D:\Staxrip.2.0.2.4.x64\v4.8\Apps\Plugins\Both\FFMS2\ffmsindex.exe "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv" "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).ffindex"
> 
> Writing index... Error writing index: Failed to open 'D:\Torrent\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01ï½ž02è©± (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC).ffindex'
> 
> ----------------------- Indexing using ffmsindex -----------------------
> 
> D:\Staxrip.2.0.2.4.x64\v4.8\Apps\Plugins\Both\FFMS2\ffmsindex.exe "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv" "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).ffindex"
> 
> Writing index... Error writing index: Failed to open 'D:\Torrent\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01ï½ž02è©± (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC).ffindex'
> 
> Start:    15.14.49
> End:      15.14.52
> Duration: 00:00:02
> 
> ------------------------------ Exception ------------------------------
> 
> StaxRip.ErrorAbortException: Indexing using ffmsindex failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 
> 
> ----------------------- Indexing using ffmsindex -----------------------
> 
> D:\Staxrip.2.0.2.4.x64\v4.8\Apps\Plugins\Both\FFMS2\ffmsindex.exe "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).mkv" "D:\Torrent\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01～02話 (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger グリザイア：ファントムトリガー THE ANIMATION 第01話 「EPISODE 01_SORD」 (BD 1920x816p AVC FLAC).ffindex"
> 
> Writing index... Error writing index: Failed to open 'D:\Torrent\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01ï½ž02è©± (BD 1920x816p AVC FLAC)\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC)_temp\[UCCUSS] Grisaia Phantom Trigger ã‚°ãƒªã‚¶ã‚¤ã‚¢ï¼šãƒ•ã‚¡ãƒ³ãƒˆãƒ ãƒˆãƒªã‚¬ãƒ¼ THE ANIMATION ç¬¬01è©± ã€ŒEPISODE 01_SORDã€ (BD 1920x816p AVC FLAC).ffindex'
> 
> 
>    at StaxRip.Proc.Start()
>    at StaxRip.GlobalClass.ffmsindex(String sourcePath, String cachePath, Boolean indexAudio, Project proj)
>    at StaxRip.MainForm.Indexing()
>    at StaxRip.MainForm.Demux()
>    at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding)
> 

Any help?

**Comment by fmohican** [comment]
try to rename file & path to `Grisaia Phantom Trigger`
I mean remove any "non-ascii" character from file name / folder name
