### ISSUE TITLE
VUI Import not correct

### ISSUE THREAD

**Issue by ccaptain00** [Revan654/staxrip#106]
I have not tried 2.0.4.0 yet.  Just got around to trying  2.0.3.0.  Let me know if you need more info.  I have been still using the old Stax76 build.

![Orginal](https://user-images.githubusercontent.com/36252584/64468664-79c48d00-d0f5-11e9-8fe1-03249f813862.jpg)
Original MKV ripped using MakeMKV

![1 7 0 6](https://user-images.githubusercontent.com/36252584/64468678-95c82e80-d0f5-11e9-90ad-f92b65361920.jpg)
Encoded using StaxRip 1.7.0.6.  

![1 7 0 6](https://user-images.githubusercontent.com/36252584/64468712-dde75100-d0f5-11e9-8249-96235f9a857c.jpg)
Encoded using StaxRip 2.0.3.0.  The same Versions of VapourSynth and Python were used for both encodes.  

Not sure if it really matters as most displays can't do 1000 cd/m2 let alone 4000 cd/m2.  But, it still bugs me that it doesn't match the source file.  Using MediaInfo 19.07.

**Comment by L4cache** [comment]
0.0050 / 4000 --> 0.0001 / 1000 using 2.0.4.0
source: 
![ori](https://user-images.githubusercontent.com/42721712/64500911-cb396b80-d2f1-11e9-9d46-0f8536f0123e.png)
re-encoded: 
![enc](https://user-images.githubusercontent.com/42721712/64500910-caa0d500-d2f1-11e9-86a4-2d379547302a.png)

So for the time being, you have to modify it manually, like: 
_(please don't judge my preset, just for a quick test ;p)_
![opt](https://user-images.githubusercontent.com/42721712/64501091-819d5080-d2f2-11e9-8824-aa9caa8bb305.png)
then the result will be correct: 
![fix](https://user-images.githubusercontent.com/42721712/64501119-95e14d80-d2f2-11e9-847e-9b061363d788.png)

_btw: i didn't see any difference between your pic2&3... putting same picture accidentally? ;p_

**Comment by ccaptain00** [comment]
![2 0 3 0](https://user-images.githubusercontent.com/36252584/64515625-e937a980-d2ba-11e9-86bc-bb54da24ed7a.jpg)
This was supposed to be my 3rd pic.  Encoded with 2.0.3.0
