### ISSUE TITLE
[Suggestion] Add a funtion to autodelete current tempfolder after current job

### ISSUE THREAD

**Issue by yukkodesu** [Revan654/staxrip#108]
I cant find any option to auto delete it.
It really take up huge amount of space, and become useless after transcode.
so if you dervelopers can add an option to delete temp folders after encoding, it would help;
thank you to develop this tool

**Comment by JoyBell2** [comment]
The option is already there. Unless I am not understanding.
Tools-->Settings-->System-->Delete Temp Folder
I have it set to Recycle Bin.
