### ISSUE TITLE
Error with Color AutoAdjust

### ISSUE THREAD

**Issue by JoyBell2** [Revan654/staxrip#11]
Image of the issue
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/268659/1733564/tiDlf0d5TU4oNb7/2018-06-13%2020.42.40%20%20Auto%20Levels.jpg

`AutoAdjust( gamma_limit=1.0, scd_threshold=16, gain_mode=1, auto_gain=True, auto_balance=True, Input_tv=False, output_tv=False, use_dither=False, high_quality=True, high_bitdepth=True, threads_count=2)`

I have tried using AutoAdjust with HDR, and YUV 10 and YUV 8. The result is always the same. A 1/4 or 1/2 frame of garbled image.
Also the part of the image that isn't garbled is identical to the source with no color, brightness, gamma, etc.

Just reporting the issue I've run into when I looked to use a filter to correct some color issues.

**Comment by Revan654** [comment]
You have High_BitDepth enabled, which creates a stacked video (MSB & LSB). Unless you call post at the end the video will become split.

Auto-Adjust changes based on the settings you use(Not all the settings are listed in the syntax). HDR already uses such a high level of brightness it's doubtful you see much difference. AutoAdjust was designed for non-HDR content. The Filter was designed before HDR even existed.

Not all Filters are meant for HDR.

**Comment by Revan654** [comment]
Since there been no reply for a few days, I'll take everything been resolved.

**Comment by JoyBell2** [comment]
Alright thanks. I have been doing HDR to SDR conversions for compatibility and almost all files need hand tuning to look correct in the output, I was hoping to try some of the AutoLevel functions.
