### ISSUE TITLE
Uselessly increase file size !!

### ISSUE THREAD

**Issue by Cyberavater** [Revan654/staxrip#12]
When U encode multiple files in a same folder it creates ONE temp folder and keeps encoding one after another, the problem is that it uses font files from previous encode on the next encode, As a result the last file on that folder gets font files from all the previous files which are pretty much useless for that file thus the file size is increased uselessly...

There R some Ways to this fix this issue ....

1. Create a function that deletes the temp folder after each encoding.
2. Make Staxrip create multiple temp folder, even for names that are big which current Staxrip doesn't do.
3. Make Staxrip have a note of fonts in current video, so that it doesn't ends up taking fonts from previous file.

Hope, the one who is working on Staxrip can fix this issue soon.

**Comment by Revan654** [comment]
Actually it doesn't create only one file, It creates multiple temp files based off the files you are loading.

From what I could actually understand from the post. You may want to explain in detail what you are trying to achieve.

1. You can have StaxRip delete the Temp folders once the process finishes. It's under Settings.
2. StaxRip already does create folders for larger names.
3. Not sure what you mean by this.

You also have access to batch & PowerShell Scripting.

**Comment by Cyberavater** [comment]
I think U misunderstood me I didn't said, it only creates one FILE, I said it creates only one FOLDER for multiple file with big name (i.e. It will create ONE FOLDER named ''Sword Art Onlin..._temp'' for both ''Sword Art Online Episode 01 The World of Swords.mkv'' & ''Sword Art Online Episode 02 Beater.mkv'' ; even more if U R working with more files in that same folder) . As a result when it merges the second file (i.e. Episode 02) it merges the file even with the font that did not belong to it (i.e. Episode 02) but it came from the previous file (i.e. Episode 01) since staxrip doesn't have record (note) of what actually that second file (i.e. Episode 02) had, it merged the file with the font of previous file (i.e. Episode 01). If there was more files (i.e. Episode 01~25) the last file (i.e. Episode 25 ) will get all fonts from that ONE temp FOLDER including the fonts from all previous files (i.e. Episode 01~24) which is irrelevant with that last file (i.e. Episode 25 ). Thus the later file gradually gets larger with previous irrelevant font. 

    1.You can have StaxRip delete the Temp folders once the process finishes. It's under Settings. >Then, the setting should be made default since it causes a issue.
    2.StaxRip already does create folders for larger names. > No it creates it creates only one FOLDER for multiple file with big name (i.e. It will create ONE FOLDER named ''Sword Art Onlin..._temp'' for both ''Sword Art Online Episode 01 The World of Swords.mkv'' & ''Sword Art Online Episode 02 Beater.mkv'' ; even more if U R working with more files in that same folder)
   3.Not sure what you mean by this. > Since staxrip doesn't have record (note) of what actually that second file (i.e. Episode 02) had, it merged the file with the font of previous file (i.e. Episode 01). If there was more files (i.e. Episode 01~25) the last file (i.e. Episode 25 ) will get all fonts from that ONE temp FOLDER including the fonts from all previous files (i.e. Episode 01~24) which is irrelevant with that last file (i.e. Episode 25 ).

I hope that explains it...

**Comment by almanteka** [comment]
what you have in Options > Paths > Temp Files Directory?

**Comment by Cyberavater** [comment]
It's empty.

**Comment by Revan654** [comment]
The Folders that get made to ..._Temp that is tied to Windows FileSystem IO. Which is something I can't change. Any MS metadata files in .net Framework are locked. It's a limitation of Windows OS rather then StaxRip.

The OS tries to create the Shortest path possible to the Source.

I have to see where in the source code the creation takes place.

You can try to use Batch when adding more then one file(Filters and Such must be set-up Before hand). 

Your Temp Fold Should look like something like this:

https://imgur.com/nxNlUmr

1. You can Enable it, by default files are named correctly and have srip file attached to them. 

2. That is a Windows OS issue, 

3. All files Should have a .srip file attached to them.

**Comment by almanteka** [comment]
with my suggestion my Temp folder looks like this
![staxrip temp](https://user-images.githubusercontent.com/42816936/45517325-c217cc00-b77b-11e8-8723-70a3c4e74c38.jpg)

**Comment by Cyberavater** [comment]
@almanteka Yes Ur suggestion takes care of of no. 2. Thx :)

@Revan654 
        Your Temp Fold Should look like something like this:
        https://imgur.com/nxNlUmr
Yes it does, but the problem is with fonts file, The video U chose doesn't contain font files . Just take 2 video file with fonts in a same folder then try to encode it. The later one will get font file from the previous one. ( I can upload U sample if U want. )

Since U can have StaxRip delete the Temp folders once the process finishes, then enable the option as default setting. So that, the font doesn't mess up for those who newly download this. Or, set (as default settings) Options > Paths > Temp Files Directory as %source_dir%%source_name%_temp\ That'll create multiple folder even for large name.

**Comment by Revan654** [comment]
When Creating new Temp Files it shouldn't add the ... to the folders anymore. It should create the Full name now. If you need to go beyond the 260 limit, Make sure to make proper changes to the group policy settings.

Not 100% sure why the limit was set to 30 letters before it starts to create shorter temp files.

https://i.imgur.com/HMudTtt.png

**Comment by Revan654** [comment]
I assume this is resolved since, there been no replies.

**Comment by Cyberavater** [comment]
So, where is the new fixed release?
