### ISSUE TITLE
Master display

### ISSUE THREAD

**Issue by foXaCe** [Revan654/staxrip#14]
Hello,

why the master display info do not work ?

![image 001](https://user-images.githubusercontent.com/290678/45992864-2e53d300-c08c-11e8-8701-8856d0b8c68f.jpg)

**Comment by Revan654** [comment]
Works Fine at my end.

![untitled](https://user-images.githubusercontent.com/38091898/45995546-78c25900-c066-11e8-94f8-56ab4504cd21.png)


For HDR VUI functions to autoload it must pass all the metadata checks based off HDR10 Standards. 

You Mediainfo data should look like so:

![untitled2](https://user-images.githubusercontent.com/38091898/45995640-ea020c00-c066-11e8-9737-72c59b26ac44.png)

**Comment by foXaCe** [comment]
OK, but doesn't work for me, I've tried with several movies. Maybe something I didn't understand?

**Comment by Revan654** [comment]
Whats your metadata reporting?

**Comment by foXaCe** [comment]
Color primaries          : BT.2020
Transfer characteristics : PQ
Matrix coefficients      : BT.2020 non-constant
Mastering display color primaries: Display P3
Mastering display luminance: min: 0.0050 cd/m2, max: 1000 cd/m2

**Comment by Revan654** [comment]
Color primaries : BT.2020
Transfer characteristics : PQ
Matrix coefficients : BT.2020 non-constant
**Mastering display color primaries: Display P3**
Mastering display luminance: min: 0.0050 cd/m2, max: 1000 cd/m2

There your answer, It's not BT.2020 but Display P3 instead.

**Comment by Revan654** [comment]
> It's common to master HDR content in the DCI P3 color space, with either the DCI (~D50) or D65 white points. This is not a supported format for HDR delivery to any format. When mastering, the Master Display must have Rec. 2020 color primaries (the Rec. 2100 standard implies Rec. 2020 color in many applications).
> 
> A common mistake is to master in P3, then try to tag the results using Rec. 2020 primaries. This will result in an oversaturated look with shifted hues and create Improper HDR metadata.

**Comment by foXaCe** [comment]
ok , but with version 1.8 everything work correctly

**Comment by Revan654** [comment]
Different Source Material Maybe?

The ColorCheck is the same from 1.8.
