### ISSUE TITLE
Crashes after performing autocrop and closing crop preview window

### ISSUE THREAD

**Issue by NeonZaboca** [Revan654/staxrip#15]
**Describe the bug or Issue**

**Step To Reproduce the Problem**

3. Using '...' Encoder
4. 'Avisynth or VapourSynth' Being Used 
6. Filter(s) x is being Used.
7. Any Major External Files tied to the Error.
8. Post Both your Log file & AVS/VS Script.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1803]
 - Version [e.g. 1.9]

**Additional context**
Add any other Information or additional context that can be Helpful.

**Please be Clear and as Detailed as Possible**

**Any Issues left unattended to for Length of Time will automatically be Closed Due to inactivity**

**Comment by Revan654** [comment]
Make sure your using the latest version, The first 1.9 had a small issue which has already been fixed.
