### ISSUE TITLE
no file extension for subtitles after extracting

### ISSUE THREAD

**Issue by Mister-XY** [Revan654/staxrip#16]
**Describe the bug or Issue**
If i extract a movie file with mkvextractor, the subtitles did not have any file extension. 
So, i cannot look via bdsup2sub++ if that a commentar or forced etc.
There must be an file extensions by the subtitles files.

> Extracting track 1 with the CodecID 'A_DTS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID1 German.mka'. Container format: Digital Theater System (DTS)
Extracting track 2 with the CodecID 'S_HDMV/PGS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID3 German'. Container format: SUP
Extracting track 3 with the CodecID 'S_HDMV/PGS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID4 German'. Container format: SUP
Extracting track 4 with the CodecID 'S_HDMV/PGS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID5 German'. Container format: SUP
Extracting track 5 with the CodecID 'S_HDMV/PGS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID6 German'. Container format: SUP
Extracting track 6 with the CodecID 'S_HDMV/PGS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID7 German'. Container format: SUP
Extracting track 7 with the CodecID 'S_HDMV/PGS' to the file 'E:\DVD\temp\IRON_MAN_2_t04_temp\IRON_MAN_2_t04 ID8 German'. Container format: SUP

**Step To Reproduce the Problem**

3. Using '...' Encoder
4. 'Avisynth or VapourSynth' Being Used 
6. Filter(s) x is being Used.
7. Any Major External Files tied to the Error.
8. Post Both your Log file & AVS/VS Script.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1803]
 - Version [e.g. 1.9]
version 1.9

**Additional context**
Add any other Information or additional context that can be Helpful.

**Please be Clear and as Detailed as Possible**

**Any Issues left unattended to for Length of Time will automatically be Closed Due to inactivity**

**Comment by Revan654** [comment]
Subtitles is bit out my wheelhouse, I don't know much about Subtitles. The Subtitle functions have not been touched in StaxRip. If they worked previously it should still work the same.

What do you have the Subtitle Settings set to under Options?

I can look at the code, It might be an issue with mkvextract rather then StaxRip.

**Comment by Mister-XY** [comment]
![mkv](https://user-images.githubusercontent.com/10309056/46038311-0788b180-c10b-11e8-8d28-19652ac3c76b.png)
On the left side, this in version 1.8.2.0 and on the right side on the new 1.9.0 version.

**Comment by Revan654** [comment]
First Try this:

[StaxRip.AlteredSubtitleCode.zip](https://github.com/Revan654/staxrip/files/2417114/StaxRip.AlteredSubtitleCode.zip)

It's an Altered version with a few tweaks to Subtitle Code. If that fails try the Following:

Theory:

1. Mediainfo is isn't returning any data to Subtitles when it scans the file. It's just returning some null data file.
2. Demuxer being used can't fully read the subtitles inside the file or there a bug in one of the exe files which is creating issues when reading.

Options you can try:

Revert back to MediaInfo 18.05
Revert Back to MKVExtract 23
Revert Back to MP4Box 0.7.2 (Non-Nightly Build)

Download Build 1.8.2.0

Delete MediaInfo, MKVNix & MP4Box Folders and use the folders from 1.8.

Then Check and see if you get the any changes.

**Comment by Mister-XY** [comment]
Allways is correct with Mediainfo 18.05. There must be an error with the new mediainfo.

**Comment by Revan654** [comment]
You might want to report that to MediaInfo.

**Comment by JeromeMartinez** [comment]
> There must be an error with the new mediainfo.

@Mister-XY MediaInfo developer here.
No regression with the files I have (MediaInfo side). Please provide a sample file which was working previously and does not work anymore.

**Comment by Mister-XY** [comment]
@Revan654 . with the mediainfo 18.0.8.1, there are no correct file extensions. (sup, dts etc.).
And i think, there is an problem in interface between mediainfo and staxrip. 
And i can't gave you a sample because the infos in mediainfo are correct. The must be an problem in staxrip and mediainfo. Did you change the api?

**Comment by JeromeMartinez** [comment]
> Did you change the api?

Deprecated fields are no more available by default.
@Revan654 you may try by setting an option MediaINfo::Option("Legacy", "1") and see if the problem is still there.

**Comment by JeromeMartinez** [comment]
> AAC(it should return m4a extension with the code) 

AAC file analysis should **never** return "m4a". "m4a" is an extension for MP4 container format (AAC is often transported by MP4, but not always the case, it can also be transported by Matroska container which has the extension "mka".). Actually, "AAC" does not exists as a file format (it needs a container), so no extension could be associated with AAC.
If you want me to try to help, please let's speak the same language.

> However it's now returning mka instead.

So Matroska container. Not incompatible with AAC audio.
What is the output for MediaInfo 18.08 GUI?
How is used MediaInfo library?
What is the result of MediaInfo::Inform() in your program?

**Comment by Revan654** [comment]
I wasn't thinking clearly last night, to much going on. To be clear on the issue:

The default file: trailer_1500.mp4

Demuxing Process via MP4 with the return code using 18.05:

C:\Users\Revan\Desktop\staxrip-1.8.2.0\bin\x64\Apps\MP4Box\MP4Box.exe -single 2 -out "C:\Users\Revan\Desktop\trailer_1500_temp\trailer_1500 ID1 English.m4a" C:\Users\Revan\Desktop\trailer_1500.mp4

```

General
Complete name         : C:\Users\Revan\Desktop\trailer_1500_temp\trailer_1500 ID1 English.m4a
Format                : MPEG-4
Format profile        : Base Media
Codec ID              : isom (isom)
File size             : 247 KiB
Duration              : 42 s 592 ms
Overall bit rate mode : Variable
Overall bit rate      : 47.5 kb/s
Encoded date          : UTC 2018-09-27 03:18:52
Tagged date           : UTC 2018-09-27 03:18:52
```

Now with latest version I wasn't getting the m4a instead it returned mka which would trigger the wrong software and it thinking it was mkv file instead of mp4.

C:\Users\Revan\Desktop\staxrip-1.8.2.0\bin\x64\Apps\MP4Box\mkvextract.exe -single 2 -out "C:\Users\Revan\Desktop\trailer_1500_temp\trailer_1500 ID1 English.mka" C:\Users\Revan\Desktop\trailer_1500.mp4

**Comment by Revan654** [comment]
I'll get you rest of the info later today(if I can). It's not easy to alter this code, One change can alter everything if I'm not careful.

**Comment by Mister-XY** [comment]
why is it closed?
