### ISSUE TITLE
Program collapse when cropping.

### ISSUE THREAD

**Issue by iAM261917** [Revan654/staxrip#20]
I clicked the crop button on the menu bar and cropped the video through the pop-up cropping window, then I closed the cropping window, the program got stuck, and it disappeared after a while.
At first, I thought that's because the resolution my video is too big(4K), but I just tried 1080p and 720p video, and got same result.

**Comment by Revan654** [comment]
Make sure you grab the newer version, It was an issue due to external source. Which has been fixed.

**Comment by iAM261917** [comment]
@Revan654 Mine is version 1.9.0.0, it's your latest release.
