### ISSUE TITLE
Compressibility Check using x265 2.8+69 failed with exit code: -1073741795 (0xC000001D)

### ISSUE THREAD

**Issue by ikka007** [Revan654/staxrip#24]
Hi Revan654, Just tried the v1.9.0.0 but got this error. Log is here -
 (with path omitted for obvious reasons )
--------------------
Error Compressibility Check using x265 2.8+69 (1.9.0.0)

Compressibility Check using x265 2.8+69 failed with exit code: -1073741795 (0xC000001D)

The exit code might be a system error code: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.

--------------- Compressibility Check using x265 2.8+69 ---------------

"D:\....\StaxRip [x64]\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "C:\Users\....\Stax-Rips\--[6] BTS-001_temp\--[6] BTS-001--XMr.P2dX_CompCheck.avs" | "D:\...\StaxRip [x64]\Apps\x265\x265.exe" --crf 18 --profile main10 --transfer bt709 --frames 448 --y4m --output "C:\..\Stax-Rips\--[6] BTS-001_temp\--[6] BTS-001--XMr.P2dX_CompCheck.hevc" -

avs2pipemod[info]: writing 448 frames of 30000/1001 fps, 720x400,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 3.846 sec.
avs2pipemod[error]: only wrote 0 of 448 frames.

StaxRip.ErrorAbortException: Compressibility Check using x265 2.8+69 failed with exit code: -1073741795 (0xC000001D)

The exit code might be a system error code: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.

--------------- Compressibility Check using x265 2.8+69 ---------------

"D:\....\StaxRip [x64]\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "C:\Users\....\Stax-Rips\--[6] BTS-001_temp\--[6] BTS-001--XMr.P2dX_CompCheck.avs" | "D:\...\StaxRip [x64]\Apps\x265\x265.exe" --crf 18 --profile main10 --transfer bt709 --frames 448 --y4m --output "C:\..\Stax-Rips\--[6] BTS-001_temp\--[6] BTS-001--XMr.P2dX_CompCheck.hevc"  -

avs2pipemod[info]: writing 448 frames of 30000/1001 fps, 720x400,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 3.846 sec.
avs2pipemod[error]: only wrote 0 of 448 frames.

   at StaxRip.Proc.Start() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\Proc.vb:line 338
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Encoding\x265Enc.vb:line 65
   at StaxRip.x265Enc.RunCompCheck() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Encoding\x265Enc.vb:line 105

**Comment by Revan654** [comment]
If the paths come close to 256ish characters, Then you need to enable Longpaths.

**Comment by OnbekendHH** [comment]
Hey, thanks for the response!

 

Where do I enable Longpaths?

**Comment by Revan654** [comment]
In groupPolicy or if you know what your doing regedit.

Also when you install Python, it gives you the option to enable it as well.
