### ISSUE TITLE
File in use error after processing is finished

### ISSUE THREAD

**Issue by 44vince44** [Revan654/staxrip#26]
Hi Revan,

When you process a file, and the processing is finished, you can't delete the source file unless you
close staxrip. 

**Step To Reproduce the Problem**

1. open a file for processing, use compressor x265 and qaac (or any)
2. Add job (only one job in the list), start job wait the job to finish
3. when finished  the job list is empty, the program window is empty also (no project)
4. try to delete the source file, Windows says you can not because the file is still
    in use. So you need to close Staxrip program, although there is no project open.

Sorry for the double post with Stax76 issue#418, I thought you were still using Stax76 issue page.
And thank you very much.

**Comment by Revan654** [comment]
That's due to dotnet 4.7.2, Windows 10 Security locks, You can just use Delete Temp Folder option, Which will remove the folder once it's done encoding.
