### ISSUE TITLE
ConvertToRGB calls 8 plugins that are not required

### ISSUE THREAD

**Issue by 44vince44** [Revan654/staxrip#27]
Hi Revan and all people here,

Description: when I add the filter ConvertToRGB() or ConvertToRGB24() and 32, 48 etc

it will call all the following:
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\avs\AddGrainC\AddGrainC.dll")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\avs\Average\Average.dll")
Import("C:\Program Files\StaxRip\Apps\Plugins\avs\DehaloAlpha\Dehalo_alpha.avsi")
Import("C:\Program Files\StaxRip\Apps\Plugins\AVS\NNEDI3\edi_rpow2.avsi")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\avs\JPSDR\Plugins_JPSDR.dll")
LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\avs\modPlus\modPlus.dll")
Import("C:\Program Files\StaxRip\Apps\Plugins\AVS\NNEDI3\nnedi3.avsi")
Import("C:\Program Files\StaxRip\Apps\Plugins\AVS\Utils\Utils-1.avsi")
(They appear in the code preview and in the final code of the job)

The consequence is that when I press preview, it takes 10 seconds to open the preview, when I press Next to create the job, also it takes 10 seconds. Everything else works fine.

Please  note that ConvertToYUV filter family does not call any of these plugins.
Please note also that this problem did not exist in Staxrip v1.7.0.6: ConvertToRGB filters didn't call any plugin to load or to import.

Again, sorry with the double post in Stax76 page issue#417

Thanks for the good work!!

**Comment by Revan654** [comment]
Utils script has ConvertToRGB() as Well. It calls Utils Script which triggers loading of all the additional plugins it needs as well. I might remove it down the road, I'll see what is needed.

If a Plugin is loaded but not used, there zero consequences. If it takes you more then 3 seconds for preview window to appear, then something else wrong (Very likely some Hardware issue).

You can't compared 1.7.0.6 to Newer versions two very different set of filters & plugins are used.

**Comment by 44vince44** [comment]
Thanks very much for taking a look at it !!

**Comment by 44vince44** [comment]
And thank you very much for having fixed it in v2.0.0.0
