### ISSUE TITLE
Failed to open VapourSynth script ver 1.9.0.0

### ISSUE THREAD

**Issue by sshirey76** [Revan654/staxrip#28]
Hi Revan: I noticed that the stack on failure has the following which I assume is part of the problem when running VS..  For some reason it is using the following home directory:
C:\Users\Revan\Desktop\staxrip-1.8.2.0\

at StaxRip.AVIFile..ctor(String path) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\AVIFile.vb:line 50
at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\VideoScript.vb:line 202
at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Forms\MainForm.vb:line 2082

**Comment by Revan654** [comment]
Without a Log I can't really do anything. What you posted is just where code triggers.

**Comment by Revan654** [comment]
> 
> 
> Sorry man here you go. I just ran it again to replicate.
> #28

Where? You just linked to this thread.

**Comment by sshirey76** [comment]
[Hugo (2011)_staxrip.log](https://github.com/Revan654/staxrip/files/2512937/Hugo.2011._staxrip.log)

**Comment by sshirey76** [comment]
Sorry Revan,  kind of new and this drag and drop didnt work I guess.  Hopefully now you can see it with the manual add.

**Comment by sshirey76** [comment]
You will notice it says plugin folder not found but it is there so I looked at the permissions and they have full access for my id and admin.

**Comment by Revan654** [comment]
It's your Python Search Path. You also have to make sure your using Python 3.6 with R44.

**Comment by sshirey76** [comment]
oh ok.  Yes I had R45 and Python 3.7.1 installed.  I will clean deinstall and then install 3.6 with R44 and see how it goes.  Thank you.

**Comment by Revan654** [comment]
the r should be right before the string source. It's all correct, It still your Search Path, When you install Python, make sure you check Include python in the search path.

It seems you are also missing: Plugin directory is missing!

I would also check make sure you have read, write & execute access to StaxRip. It's why the Docs says not to install it in ProgramFiles folder.
