### ISSUE TITLE
AVIFileOpen failed to execute

### ISSUE THREAD

**Issue by Hesham3del** [Revan654/staxrip#29]
Hello Revan,

This is the first time ever for me to use Staxrip as I want to convert a .mkv movie into .avi (Xvid) format.

I tried uninstalling and reinstalling and restarting the machine with no luck to get rid of the below error.

I don't know what to do ?!

Exception (1.9.0.0)

AVIFileOpen failed to execute

Failed to open AviSynth script:

C:\Users\Hisham\Desktop\1_temp\1_new_source.avs

You can try to open the script with VirtualDub x64, if it don't open it could be a problem with the script or the AviSynth+ x64 setup, if StaxRip don't report a script error and the script looks valid then reinstalling AviSynth+ x64 might fix the problem, the setup is located at:

C:\Users\Hisham\Downloads\StaxRip-x64-1.9.0.0\Apps\AviSynthPlus-MT-r2728.exe

System.Exception: AVIFileOpen failed to execute

Failed to open AviSynth script:

C:\Users\Hisham\Desktop\1_temp\1_new_source.avs

You can try to open the script with VirtualDub x64, if it don't open it could be a problem with the script or the AviSynth+ x64 setup, if StaxRip don't report a script error and the script looks valid then reinstalling AviSynth+ x64 might fix the problem, the setup is located at:

C:\Users\Hisham\Downloads\StaxRip-x64-1.9.0.0\Apps\AviSynthPlus-MT-r2728.exe

   at StaxRip.AVIFile..ctor(String path) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\AVIFile.vb:line 50
   at StaxRip.VideoScript.Synchronize(Boolean convertToRGB, Boolean comparePath) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\VideoScript.vb:line 202
   at StaxRip.MainForm.ModifyFilters() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Forms\MainForm.vb:line 2281
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Forms\MainForm.vb:line 1997

**Comment by sshirey76** [comment]
FYI I have reported this issue as part of #28 actually.  I still have that same problem after Python 3.6 and VS R44 installed as well as setting the PythonPath and path accordingly.

**Comment by Revan654** [comment]
if your having issues opening video file, Try installing LAVFilters Which is also included with StaxRip.

**Comment by Hesham3del** [comment]
Forget to thank you for keeping up with me and editing the reply more than once to help me Revan, much appreciated brother 👍

**Comment by Revan654** [comment]
Downloading from github is working just fine.

I wouldn't use the files from videohelp, that build is from Alpha Stage. Site never updated to latest version. 

If your only planning on using AVS you don't need VS or Python.

it seems your PC isn't registering the keys when you install Avisynth or Avisynth isn't install the dll to System folder. You should see avisynth.dll in your System Folder. I would also check App Manager to see if you have any warnings. You can ignore wrong or outdated version msgs.
