### ISSUE TITLE
 Video encoding using QSVEnc 3.05

### ISSUE THREAD

**Issue by proper88** [Revan654/staxrip#3]
I alway get this error when using QSVEnc

C:\Temp\bluraytools\StaxRip\Apps\QSVEnc\QSVEncC64.exe --codec hevc --profile main10 --weightb --weightp --colorprim bt2020 --transfer smpte2084 --fallback-rc --i-adapt --icq 23 -i "D:\Filme\test.avs" -o "D:\Filme\test.hevc"

Error: Unknown value "bt2020" for "--colorprim"

**Comment by Revan654** [comment]
I have no way to test QuickSync in HEVC. I can only use the documentation that was released with QSVENCc. 

Link: https://github.com/rigaya/QSVEnc/blob/master/QSVEncC_Options.ja.md

As you can see BT2020 is the correct syntax. I would double check the version just to make sure it's using the latest release. Check your hardware too to see if you can use all the options.

**Comment by proper88** [comment]
You are right, i also run a test with old version 2.75, your command is working perfectly.

When i remove --colorprim then i get the next error
Error: Unknown value "smpte2084" for "--transfer"
after removing --transfer, decoding starts, check output file video looks OK
Do you know the meaning of options  --colorprim, --transfer ?, maybe these options are not necessary

**Comment by Revan654** [comment]
There all part of the ColorSpace, Used to map the ColorSpace to the video.

Prim: Rec.2020 = Used for 4K Content. HD - BT 709
Transfer: ST2084: Used for HDR. SDR - BT 709
Matrix: bt2020nc for HDR. SDR - BT 709

Prim = Color Primaries 
Transfer = Color Transfer (some Contain the Gamma Data like ST2084)

If your encoding HDR content they are required along with other options.

Beware some of the source code files are for Linux. I would have to go through all the code to see if Rec.2020 is supported on Windows or not.

I would ask the developer about the colorspace options, He will be able to give you a absolute answer on the matter. I'm basing the encoder on the documentation which is suppose to include all the functions and syntax. The only thing I can think of why it's include in the doc and doesn't work is the function is planned but not fully functional yet. That or it was a mistype(or copy and paste job from NVENCc).

**Comment by proper88** [comment]
QSVEncC 3.03 is working, all others(3.04, 3.05, 3.06) not, we have to wait for a statement from rigaya.

**Comment by Revan654** [comment]
Were they working with the ColorSpace Like BT 2020? After doing a global search of the code. There are zero references to ST 2084 or Rec 2020.

**Comment by Revan654** [comment]
1. it's missing a bunch of flags that are required to enable HDR.
2. Display P3 is not consider part of the HDR color, it requires Rec.2020.
3. You need the Color Coordinates injected into the file.
4. Just be aware H.265 and x265 are two different types of compressions under HEVC. Right now HDR can only be done correctly under x265.
