### ISSUE TITLE
Update Fails Path is broken

### ISSUE THREAD

**Issue by sshirey76** [Revan654/staxrip#30]
Load StaxRip
Go To:  Tools > Advanced > Check For Update

Result:
Popup "Application Will Shutdown to Check for Updates"
User Clicks: OK

StaxRip popup message is presented:
The system cannot find the file specified
File: C:\Program
Arguments: Files\StaxRip\Update.bat

**Comment by sshirey76** [comment]
Attempting to run the batch file directly appears work as expected FYI.  Issue appear to only occur in the calling of the file within the GUI.

**Comment by Revan654** [comment]
You can not run it from Programs Folder. Since it needs Write Access.
