### ISSUE TITLE
ffmpeg needs VSScript.dll?

### ISSUE THREAD

**Issue by canfoderiskii** [Revan654/staxrip#32]
**Describe the bug or Issue**
In the log file I can find something like this:
_Find Gain 1 using FFmpeg 2018-10-26 failed with exit code: -1073741515 (0xC0000135)_

If I execute command `c:\staxrip\Apps\ffmpeg\ffmpeg -version`, it says VSScript.dll is missing.
I also tried the same command with the FFmpeg shipped with staxrip 1.9.0.0 and it works without error.

I copy a `VSScript.dll` from the one shipped with `VapourSynth R45` into path `c:\staxrip\Apps\ffmpeg\`, then FFmpeg works fine.

**Comment by Revan654** [comment]
You can install VapourSynth or Replace it with the latest static build both work without any issues.

**Comment by canfoderiskii** [comment]
@Revan654 Thank you for the reply.

BTW, I am trying to use the portable version of VapourSynth, because VapourSynth installer keeps saying that it needs python 3.7. But I have Anaconda that provides Python 3.7 already. I just can't install VapourSynth via installer.

**Comment by canfoderiskii** [comment]
@Revan654 How should I change the registry to make it work then? I have no clue.
