### ISSUE TITLE
Video encoding using x265 2.8+69 failed with exit code: -1073741795 (0xC000001D)

### ISSUE THREAD

**Issue by ikka007** [Revan654/staxrip#33]
**So here's the error again that generated , tho this time I tried with fresh install and default settings with LONG PATHS enabled but x265 encoder still gives up and ends up with this :**

------------------
Error Video encoding using x265 2.8+69 (1.9.0.0)

Video encoding using x265 2.8+69 failed with exit code: -1073741795 (0xC000001D)

The exit code might be a system error code: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.

------------------- Video encoding using x265 2.8+69 -------------------

"C:\Portables\StaxRip-x64-1.9.0.0\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "C:\Users\Useranon\Videos\Aquaman - Extended Trailer_temp\Aquaman - Extended Trailer.avs" | "C:\Portables\StaxRip-x64-1.9.0.0\Apps\x265\x265.exe" --crf 26 --profile main10 --frames 7611 --y4m --output "C:\Users\Useranon\Videos\Aquaman - Extended Trailer_temp\Aquaman - Extended Trailer_out.hevc" -

avs2pipemod[info]: writing 7611 frames of 24000/1001 fps, 1280x720,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 14.625 sec.
avs2pipemod[error]: only wrote 0 of 7611 frames.

StaxRip.ErrorAbortException: Video encoding using x265 2.8+69 failed with exit code: -1073741795 (0xC000001D)

The exit code might be a system error code: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.

------------------- Video encoding using x265 2.8+69 -------------------

"C:\Portables\StaxRip-x64-1.9.0.0\Apps\avs2pipemod\avs2pipemod64.exe" -y4mp "C:\Users\Useranon\Videos\Aquaman - Extended Trailer_temp\Aquaman - Extended Trailer.avs" | "C:\Portables\StaxRip-x64-1.9.0.0\Apps\x265\x265.exe" --crf 26 --profile main10 --frames 7611 --y4m --output "C:\Users\Useranon\Videos\Aquaman - Extended Trailer_temp\Aquaman - Extended Trailer_out.hevc" -

avs2pipemod[info]: writing 7611 frames of 24000/1001 fps, 1280x720,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 14.625 sec.
avs2pipemod[error]: only wrote 0 of 7611 frames.

   at StaxRip.Proc.Start() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\Proc.vb:line 338
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Encoding\x265Enc.vb:line 65
   at StaxRip.x265Enc.Encode() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\Encoding\x265Enc.vb:line 41
   at StaxRip.GlobalClass.ProcessVideo() in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\GlobalClass.vb:line 231
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in C:\Users\Revan\Desktop\staxrip-1.8.2.0\General\GlobalClass.vb:line 138

**Comment by Revan654** [comment]
It's very likely your filters or your CPU doesn't support the filter being used.
