### ISSUE TITLE
StaxRip not exiting by itself after converting TS files

### ISSUE THREAD

**Issue by maupassant2** [Revan654/staxrip#36]
StaxRip converts the TS file to MP4, as I asked, but for some reason it doesn't exit (file or folder in use). I have to click Cancel on the "folder in use" warning and then close StaxRip myself. Very annoying when you want to convert a batch of TS files.

**Step To Reproduce the Problem**

3. Using any Encoder
4. 'Avisynth Being Used 
6. Any filter being Used.

**Screenshots**
Included
![capture](https://user-images.githubusercontent.com/29265636/47749716-17446a00-dc64-11e8-8768-752431447799.PNG)
[Vérités et conséquences avec Louis T S01E20_ICI TOU.TV_2017_03_17_staxrip.log](https://github.com/Revan654/staxrip/files/2531591/Verites.et.consequences.avec.Louis.T.S01E20_ICI.TOU.TV_2017_03_17_staxrip.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Versions 1.9.0.0 and 2.0.0.0

**Comment by Revan654** [comment]
> It’s not recommended to start StaxRip from a location without full write, Read & Excute access so locations like ‘C:\Program Files’ shouldn’t be used. StaxRip utilizes dozens of tools and some of this tools might require write access to their start-up directory.

^This is likely your issue.

**Comment by maupassant2** [comment]
I do not start StaxRip from C:\Program Files but from a folder I created myself called "PROGRAMMES INSTALLÉS 2017 (2)", folder located on the main C drive, with a "StaxRip" subfolder. Also, this problem started with your 1.9.0.0 version and I am pretty sure someone mentioned it in the StaxRip support thread at Doom9. I thought the issue would be fixed with the next version and obviously it has not.

**Comment by Revan654** [comment]
Special Characters have problems processing through some of the 3rd party apps, Which is likely locking everything up.
