### ISSUE TITLE
Question : why is microsoft locking input source files after encoding is finished and not the output files?

### ISSUE THREAD

**Issue by 44vince44** [Revan654/staxrip#37]
Hi Revan,

is there a difference between:
   - the method used to open files for stream **reading** (case of the Source file) 
   - the method used to open files for  **writing** (case of the output encoded files in the temp folder)
???
Because the source file is still locked after the job is finished, but the output file and the temp folder are NOT locked (and moved to trash or deleted).
So why would dotnet lock the source file and not the destination. Is it a possible bug in dotnet? or a difference in the method used (in staxrip) to open for reading and open for writing? Please note that my UAC is set to minimum setting: off.

**Comment by fmohican** [comment]
Hi, as fair as I know, staxrip ins't locked any file after encode is done.

**Comment by 44vince44** [comment]
This is strange fmohican. Example: I have a job list with 5 jobs, using 5 different source files, when the jobs are all finished, I can NOT delete any of the source files if Staxrip is open. I get error "file is in use in staxrip". But all the output files (in the temp folder) can be deleted. If I want to delete a source file of a job that has finished, I need to wait that ALL jobs are finished, so I can quit staxrip, and finally delete the source files.

Revan said it is due to how dotnet 4.7.2 controls the files. Would that mean that the only workaround is to add an option to delete SOURCE files to the recycle bin, so that the source file will be moved by the staxrip process itself ? (dangerous, no ?)

Or wait that dotnet changes this behaviour (if it will happen...)

(I am running Windows 10 updated to latest, and UAC is set to the minimum.)

**Comment by Revan654** [comment]
to prevent crashing, If VB reads a null value it crashes the software.

Dotnet 4.8 is set to be released in 2019.

**Comment by HansGr00ber** [comment]
I've just tried your latest beta (2.0.0.0 beta 2) using dotnet 4.8 and I'm still having issues with the files being locked. Is there any workaround or solution? Thanks.

**Comment by fmohican** [comment]
@Revan654 isn't any workaround we can do to fix this problem?
