### ISSUE TITLE
Source filename too long causes DirectoryNotFound on (im assuming a File.OpenRead?)

### ISSUE THREAD

**Issue by imPRAGMA** [Revan654/staxrip#39]
This is the filename causing the issue:
The.Walking.Dead.S01E01.Days.Gone.Bye.BluRay.1080p.DTSHD-MA.h264.Remux-decibeL

**Comment by imPRAGMA** [comment]
P.S DirectoryNotFound in instances related to opening file is very often related to "Invalid path" errors, not an actual Directory Not Found issue.

**Comment by Revan654** [comment]
I see someone didn't read the docs, Like I said in the doc enable the long path support if you run into paths being to long.
