### ISSUE TITLE
Master Display

### ISSUE THREAD

**Issue by foXaCe** [Revan654/staxrip#4]
hello the Master display on Nvidia h265 is always missing

![image 001](https://user-images.githubusercontent.com/290678/41450046-63fef48e-7065-11e8-93de-15e2dad08d0e.jpg)

**Comment by Revan654** [comment]
Like I said previous, Mediainfo no longer displays the coordinates. Which makes it impossible to autoload the correct master-Display data. 

Data Only Shows the following Now:

Master-Display: BT.2020

Only option that would work now is if I use a static Master-Display Number for BT.2020. However each monitor has a different Master-Display loadout. It would be loading a incorrect data.

**Comment by foXaCe** [comment]
ok, how to extract data. what tools to use?

**Comment by foXaCe** [comment]
perhaps use old version of media info

**Comment by Revan654** [comment]
Older version is not 100% compliant with HDR10 & HDR10+. 
----------
You can't extract the data for Master-Display, not unless the encoding setting are left untouched(Studios remove that data). That only applies to HDR formats that are single formats.

You can try to use mkvinfo and see if it will give you any additional data and go from there.

**Comment by foXaCe** [comment]
ok thank.
i use old version of media info on your version and all work good

**Comment by Revan654** [comment]
Old versions reports the wrong color in some of the fields.
