### ISSUE TITLE
Settings lost when doing batches

### ISSUE THREAD

**Issue by VEGAX265** [Revan654/staxrip#40]
**Any Pre-Releases / Beta Releases**
none
version 2.0.0.0

**Describe the bug or Issue**
I have a Template that loads at startup with my video encoder and audio encoder settings saved.  I frequently change the output files size via the size drop down menu or by typing it in.   After selecting my files for batch mode I get an unwanted "Please select a template" menu.  I select the same custom template that is loaded at startup.  This overwrites any changes made to the template that was loaded on startup.  My sizes and settings that I initially entered on the main screen are lost.

**Step To Reproduce the Problem**

1. Open staxrip with a custom template loaded at startup
2. Change the file size
3. Click on source/open/file batch/add/add files
4. Select your desired videos click open
5. Click ok
6. Menu appears
7. On jobs screen click load and you will see that the settings changed back to the default templates

Note the file size 1500 has changed back to 203, the initial setting of the template.
If possible, add screenshots to help explain your problem.
![menu before](https://user-images.githubusercontent.com/44779244/48011532-ef368a00-e0ed-11e8-8030-6b8bd3d44878.jpg)
![menu after 1](https://user-images.githubusercontent.com/44779244/48011542-f6f62e80-e0ed-11e8-8764-5c8bd06b8b18.jpg)
![menu after 2 loaded](https://user-images.githubusercontent.com/44779244/48011546-f9f11f00-e0ed-11e8-8d94-9eb1cdc04b7c.jpg)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Build 1803
 - Version 2.0.0.0

**Additional context**
Add any other Information or additional context that can be Helpful.
I am running this by double clicking the staxrip.exe file.
I don't run any special commands on it that I know of.
this problem repeated on a clean install on a new computer.

I think the online documentation talks about this in 6.2.2 -AddJob:showConfirmation,templateName
templateName: Name of the template to be loaded after the job was added. Empty to load no template.
Adds a job to the job list.

I am not sure if this is related or not.

**Comment by Revan654** [comment]
I would take a look at your settings folder and make sure the .dat and Template folder are named correctly.

You are using a Beta Release, so bugs are expected. It's a risky using Beta Releases. 2.0 Final has not been Released yet.

**Comment by VEGAX265** [comment]
Sorry to seem really dumb on this i thought i was on a Final as it says stable on  my info screen.  Will it say final for final releases instead of stable?
![image](https://user-images.githubusercontent.com/44779244/48036454-80315380-e136-11e8-8d25-5e2d6a74d18e.png)

**Comment by Revan654** [comment]
> 
> 
> Sorry to seem really dumb on this i thought i was on a Final as it says stable on my info screen. Will it say final for final releases instead of stable?
> ![image](https://user-images.githubusercontent.com/44779244/48036454-80315380-e136-11e8-8d25-5e2d6a74d18e.png)

Info Screen is Based on odd or Even Numbers. odd = UnStable, Even = Stable.

Take Whats Posted as Fact, Allot of the info Screens Need to be Updated.
