### ISSUE TITLE
2.0.0.0 Not importing HDR Master Display

### ISSUE THREAD

**Issue by ccaptain00** [Revan654/staxrip#42]
![vs](https://user-images.githubusercontent.com/36252584/48240326-6f841600-e3a0-11e8-9f9b-aeebdd66b564.jpg)
![incred](https://user-images.githubusercontent.com/36252584/48240387-993d3d00-e3a0-11e8-84d8-7afff532f367.jpg)

I recently tried 2.0.0.0.   I had been using 1.7.0.6.  The settings are the same.  I am missing HDR info after encoding with 2.0.0.0.   2.0.0.0 is not automatically importing the Master Display like 1.7.0.6 did.

**Comment by Revan654** [comment]
MediaInfo has changed, It longer outputs all Color Coordinates, Due to this allot of data reading had to be changed. StaxRip currently only supports HDR10  Standards. The ColorSpace must be BT.2020 If it reads anything else it will reject the MasterDisplay data. 

HDR10 = BT.2020 & ST.2084 or BT.2100.

**Comment by ccaptain00** [comment]
I updated StaxRip 1.7.0.6 to MediaInfo 18.08.1 and it stopped importing the Master Display data, so I guess MediaInfo is causing this.

I rip all my 4K UHD disc with MakeMKV, and with almost all of my UHD disc rips the ColorSpace is YUV, the Color Primaries is BT.2020, and the Mastering Display Color Primaries is Display P3. 

I could manually input the P3 coordinates and Mastering Display Luminance, but that seems like an awful amount of work when it used to import automatically.  Or, is that information not really needed?  I am only concerned with maintaining the HDR10 which is the disc standard and not HDR10+ or DolbyVision, none of which my TVs support anyways.

In the meantime, I guess I will go back to using 1.7.0.6 as I was happy with the results and it maintained all of the information.  I have seen the Mastering Display Luminance vary greatly from disc to disc and my thought is that they wouldn't include that if it wasn't needed.

**Comment by Revan654** [comment]
MediaInfo removed The color Coordinates which directly ties to MasterDisplay VUI Import function.

Old MediaInfo Was always reporting improper Color Matrix, No matter what version your going to use, It will not import all the proper data.

It's just going take some time to add additional functions to cover all the different HDR formats.

FYI, old version doesn't inject the remain HDR10 metadata, Which new version does.

HDR10+ is another giant PIA. Which hasn't not been fully added to x265. Dolby Vision requires double layer container.
