### ISSUE TITLE
Memory Usage/Leak of 2.0.0.0 Beta 2 DotNet 4.7

### ISSUE THREAD

**Issue by darkman1983** [Revan654/staxrip#44]
There seems to be some memory leaks or something else, on 1.8.2 StaxRip only uses 32-60MB of RAM...
at 1.9.0.0+ Memory usage goes up to eg. 6GB of RAM.
As you can see here on StaxRip 2.0.0.0 Beta 2 👎 
![2018-11-18 05_11_07-task-manager](https://user-images.githubusercontent.com/553212/48668556-a40a7700-eaf0-11e8-8378-daf7b7a2ee1a.png)

**Comment by darkman1983** [comment]
Starting an encoding job 2-3 times gives than this result:
![2018-11-18 05_21_27-task-manager](https://user-images.githubusercontent.com/553212/48668606-f5673600-eaf1-11e8-86e5-87a56d12bb09.png)

**Comment by Revan654** [comment]
StaxRip is a Front End which Tunnels to the Encoder, If there is an issues it's lies with the Encoder, not with StaxRip GUI.

Without Log, AVS/VS Script and switches your using there no way I can debug this.

**Comment by darkman1983** [comment]
Currently i can't provide much in here, StaxRip closes after the inital source import, never comes back froim import, nor displays any error or anything else.
But as you can see on my Screenshot, it's clearly StaxRip GUI which eats up the RAM and not the encoder.
To get it compileing i have imported the source via SaxRip 1.8.2.0 and than opened the saved project in StaxRip 2.0.0.0 Beta 2, since it force closes on import. The same happens on the 2.0.0.0 Stable (without Beta).
Should i open another issue for the import thing?
Btw. the same happens after StaxRip finishes thes encoding und muxing...mkv is finished, but StaxRip never comes back and force closes.

Anyway, here is the import source log, nothing special in here...no errors shown.

`
-------------------------- System Environment --------------------------

StaxRip    : 2.0
Windows    : Windows 10 Pro 1803
Language   : German (Germany)
CPU        : AMD Ryzen Threadripper 2950X 16-Core Processor
GPU        : NVIDIA GeForce GTX 1050 Ti
Resolution : 1920 x 1200
DPI        : 96

------------------------ MediaInfo Source File ------------------------

D:\Video\---\---.mkv

General
Complete name                     : D:\Video\---\---.mkv
Format                            : Matroska
Format version                    : Version 4 / Version 2
File size                         : 53.9 GiB
Duration                          : 1 h 46 min
Overall bit rate                  : 72.2 Mb/s
Encoded date                      : UTC 2018-10-17 20:11:52
Writing application               : mkvmerge v27.0.0 ('Metropolis') 64-bit
Writing library                   : libebml v1.3.6 + libmatroska v1.4.9

Video
ID                                : 1
Format                            : HEVC
Format/Info                       : High Efficiency Video Coding
Commercial name                   : HDR10
Format profile                    : Main 10@L5.1@High
Codec ID                          : V_MPEGH/ISO/HEVC
Duration                          : 1 h 46 min
Bit rate                          : 64.0 Mb/s
Width                             : 3 840 pixels
Height                            : 2 160 pixels
Display aspect ratio              : 16:9
Frame rate mode                   : Constant
Frame rate                        : 23.976 (24000/1001) FPS
Color space                       : YUV
Chroma subsampling                : 4:2:0 (Type 2)
Bit depth                         : 10 bits
Bits/(Pixel*Frame)                : 0.322
Stream size                       : 47.7 GiB (89%)
Default                           : Yes
Forced                            : No
Color range                       : Limited
Color primaries                   : BT.2020
Transfer characteristics          : PQ
Matrix coefficients               : BT.2020 non-constant
Mastering display color primaries : Display P3
Mastering display luminance       : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level       : 1000 cd/m2
Maximum Frame-Average Light Level : 221 cd/m2

Audio #1
ID                                : 2
Format                            : DTS
Format/Info                       : Digital Theater Systems
Format profile                    : X / MA / Core
Codec ID                          : A_DTS
Duration                          : 1 h 46 min
Bit rate mode                     : Variable / Variable / Constant
Bit rate                          : 4 166 kb/s / 4 166 kb/s / 1 509 kb/s
Channel(s)                        : Object Based / 8 channels / 6 channels
Channel positions                 : Object Based / Front: L C R, Side: L R, Back: L R, LFE / Front: L C R, Side: L R, LFE
Sampling rate                     : / 48.0 kHz / 48.0 kHz
Frame rate                        : 93.750 FPS (512 SPF)
Bit depth                         : / 24 bits / 24 bits
Compression mode                  : / Lossless / Lossy
Stream size                       : 3.11 GiB (6%)
Title                             : Deutsch DTS:X 7.1 (UHD Blu-ray)
Language                          : German
Default                           : Yes
Forced                            : No

Audio #2
ID                                : 3
Format                            : DTS
Format/Info                       : Digital Theater Systems
Format profile                    : X / MA / Core
Codec ID                          : A_DTS
Duration                          : 1 h 46 min
Bit rate mode                     : Variable / Variable / Constant
Bit rate                          : 4 017 kb/s / 4 017 kb/s / 1 509 kb/s
Channel(s)                        : Object Based / 8 channels / 6 channels
Channel positions                 : Object Based / Front: L C R, Side: L R, Back: L R, LFE / Front: L C R, Side: L R, LFE
Sampling rate                     : / 48.0 kHz / 48.0 kHz
Frame rate                        : 93.750 FPS (512 SPF)
Bit depth                         : / 24 bits / 24 bits
Compression mode                  : / Lossless / Lossy
Stream size                       : 3.00 GiB (6%)
Title                             : English DTS:X 7.1 (UHD Blu-ray)
Language                          : English
Default                           : No
Forced                            : No

Text #1
ID                                : 4
Format                            : UTF-8
Codec ID                          : S_TEXT/UTF8
Codec ID/Info                     : UTF-8 Plain Text
Duration                          : 1 h 11 min
Bit rate                          : 0 b/s
Count of elements                 : 10
Stream size                       : 260 Bytes (0%)
Title                             : Deutsch Forced (SRT)
Language                          : German
Default                           : Yes
Forced                            : Yes

Text #2
ID                                : 5
Format                            : VobSub
Muxing mode                       : zlib
Codec ID                          : S_VOBSUB
Codec ID/Info                     : Picture based subtitle format used on DVDs
Duration                          : 1 h 43 min
Bit rate                          : 70 b/s
Count of elements                 : 11
Stream size                       : 53.2 KiB (0%)
Title                             : Deutsch Forced (VobSup)
Language                          : German
Default                           : No
Forced                            : Yes

Text #3
ID                                : 6
Format                            : PGS
Muxing mode                       : zlib
Codec ID                          : S_HDMV/PGS
Codec ID/Info                     : Picture based subtitle format used on BDs/HD-DVDs
Duration                          : 1 h 43 min
Bit rate                          : 252 b/s
Count of elements                 : 22
Stream size                       : 191 KiB (0%)
Title                             : Deutsch Forced (PGS)
Language                          : German
Default                           : No
Forced                            : Yes

Text #4
ID                                : 7
Format                            : VobSub
Muxing mode                       : zlib
Codec ID                          : S_VOBSUB
Codec ID/Info                     : Picture based subtitle format used on DVDs
Duration                          : 1 h 45 min
Bit rate                          : 7 414 b/s
Count of elements                 : 808
Stream size                       : 5.61 MiB (0%)
Title                             : Deutsch Full (VobSup)
Language                          : German
Default                           : No
Forced                            : No

Text #5
ID                                : 8
Format                            : PGS
Muxing mode                       : zlib
Codec ID                          : S_HDMV/PGS
Codec ID/Info                     : Picture based subtitle format used on BDs/HD-DVDs
Duration                          : 1 h 45 min
Bit rate                          : 27.1 kb/s
Count of elements                 : 1615
Stream size                       : 20.5 MiB (0%)
Title                             : Deutsch Full (PGS)
Language                          : German
Default                           : No
Forced                            : No

Text #6
ID                                : 9
Format                            : VobSub
Muxing mode                       : zlib
Codec ID                          : S_VOBSUB
Codec ID/Info                     : Picture based subtitle format used on DVDs
Duration                          : 1 h 45 min
Bit rate                          : 8 141 b/s
Count of elements                 : 1201
Stream size                       : 6.15 MiB (0%)
Title                             : English Full SDH (VobSub)
Language                          : English
Default                           : No
Forced                            : No

Text #7
ID                                : 10
Format                            : PGS
Muxing mode                       : zlib
Codec ID                          : S_HDMV/PGS
Codec ID/Info                     : Picture based subtitle format used on BDs/HD-DVDs
Duration                          : 1 h 45 min
Bit rate                          : 29.9 kb/s
Count of elements                 : 2401
Stream size                       : 22.6 MiB (0%)
Title                             : English Full SDH (PGS)
Language                          : English
Default                           : No
Forced                            : No

Menu
00                                : 00:00.000                             : :Kapitel 01
00                                : 02:55.925                             : :Kapitel 02
00                                : 10:19.243                             : :Kapitel 03
00                                : 15:06.614                             : :Kapitel 04
00                                : 26:39.472                             : :Kapitel 05
00                                : 29:58.213                             : :Kapitel 06
00                                : 34:41.871                             : :Kapitel 07
00                                : 38:07.493                             : :Kapitel 08
00                                : 44:55.401                             : :Kapitel 09
00                                : 55:25.488                             : :Kapitel 10
00                                : 58:39.432                             : :Kapitel 11
01                                : 01:44.742                             : :Kapitel 12
01                                : 09:24.118                             : :Kapitel 13
01                                : 12:01.025                             : :Kapitel 14
01                                : 15:22.684                             : :Kapitel 15
01                                : 20:43.171                             : :Kapitel 16
01                                : 29:58.810                             : :Kapitel 17
01                                : 34:57.316                             : :Kapitel 18
01                                : 38:04.461                             : :Kapitel 19
01                                : 39:57.032                             : :Kapitel 20

----------------- Demux MKV using mkvextract 28.2.0.7 -----------------

C:\StaxRip-2.0.0.0.Beta2.Dotnet4.7.x64\Apps\MKVToolNix\mkvextract.exe D:\Video\---\---.mkv tracks 3:"D:\Video\---\---_temp\--- ID4 German_forced.srt" 4:"D:\Video\---\---_temp\--- ID5 German_forced.idx" 5:"D:\Video\---\---_temp\--- ID6 German_forced.sup" 6:"D:\Video\---\---_temp\--- ID7 German.idx" 7:"D:\Video\---\---_temp\--- ID8 German.sup" 8:"D:\Video\---\---_temp\--- ID9 English.idx" 9:"D:\Video\---\---_temp\--- ID10 English.sup" 1:"D:\Video\---\---_temp\--- ID1 German.dtshd" 2:"D:\Video\---\---_temp\--- ID2 English.dtshd" --ui-language en

Extracting track 1 with the CodecID 'A_DTS' to the file 'D:\Video\---\---_temp\--- ID1 German.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 2 with the CodecID 'A_DTS' to the file 'D:\Video\---\---_temp\--- ID2 English.dtshd'. Container format: Digital Theater System (DTS)
Extracting track 3 with the CodecID 'S_TEXT/UTF8' to the file 'D:\Video\---\---_temp\--- ID4 German_forced.srt'. Container format: SRT text subtitles
Extracting track 4 with the CodecID 'S_VOBSUB' to the file 'D:\Video\---\---_temp\--- ID5 German_forced.sub'. Container format: VobSubs
Extracting track 5 with the CodecID 'S_HDMV/PGS' to the file 'D:\Video\---\---_temp\--- ID6 German_forced.sup'. Container format: SUP
Extracting track 6 with the CodecID 'S_VOBSUB' to the file 'D:\Video\---\---_temp\--- ID7 German.sub'. Container format: VobSubs
Extracting track 7 with the CodecID 'S_HDMV/PGS' to the file 'D:\Video\---\---_temp\--- ID8 German.sup'. Container format: SUP
Extracting track 8 with the CodecID 'S_VOBSUB' to the file 'D:\Video\---\---_temp\--- ID9 English.sub'. Container format: VobSubs
Extracting track 9 with the CodecID 'S_HDMV/PGS' to the file 'D:\Video\---\---_temp\--- ID10 English.sup'. Container format: SUP
Writing the VobSub index file 'D:\Video\---\---_temp\--- ID5 German_forced.idx'.
Writing the VobSub index file 'D:\Video\---\---_temp\--- ID7 German.idx'.
Writing the VobSub index file 'D:\Video\---\---_temp\--- ID9 English.idx'.

Start:    21:02:44
End:      21:03:25
Duration: 00:00:41

General
Complete name         : D:\Video\---\---_temp\--- ID1 German.dtshd
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : X / MA / Core
File size             : 3.11 GiB
Overall bit rate mode : Variable / Variable / Constant

Audio
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : X / MA / Core
Bit rate mode         : Variable / Variable / Constant
Bit rate              : Unknown / Unknown / 1 509 kb/s
Channel(s)            : Object Based / 8 channels / 6 channels
Channel positions     : Object Based / Front: L C R, Side: L R, Back: L R, LFE / Front: L C R, Side: L R, LFE
Sampling rate         : / 48.0 kHz / 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : / 24 bits / 24 bits
Compression mode      : / Lossless / Lossy
General
Complete name         : D:\Video\---\---_temp\--- ID2 English.dtshd
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : X / MA / Core
File size             : 3.00 GiB
Overall bit rate mode : Variable / Variable / Constant

Audio
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : X / MA / Core
Bit rate mode         : Variable / Variable / Constant
Bit rate              : Unknown / Unknown / 1 509 kb/s
Channel(s)            : Object Based / 8 channels / 6 channels
Channel positions     : Object Based / Front: L C R, Side: L R, Back: L R, LFE / Front: L C R, Side: L R, LFE
Sampling rate         : / 48.0 kHz / 48.0 kHz
Frame rate            : 93.750 FPS (512 SPF)
Bit depth             : / 24 bits / 24 bits
Compression mode      : / Lossless / Lossy

------------- Demux xml chapters using mkvextract 28.2.0.7 -------------

C:\StaxRip-2.0.0.0.Beta2.Dotnet4.7.x64\Apps\MKVToolNix\mkvextract.exe D:\Video\---\---.mkv chapters D:\Video\---\---_temp\---_chapters.xml

File 'D:\Video\---\---.mkv': container: Matroska
Track ID 0: video (MPEG-H/HEVC/h.265)
Track ID 1: audio (DTS-HD Master Audio)
Track ID 2: audio (DTS-HD Master Audio)
Track ID 3: subtitles (SubRip/SRT)
Track ID 4: subtitles (VobSub)
Track ID 5: subtitles (HDMV PGS)
Track ID 6: subtitles (VobSub)
Track ID 7: subtitles (HDMV PGS)
Track ID 8: subtitles (VobSub)
Track ID 9: subtitles (HDMV PGS)
Chapters: 20 entries

Start:    21:03:25
End:      21:03:25
Duration: 00:00:00

------------- Demux ogg chapters using mkvextract 28.2.0.7 -------------

C:\StaxRip-2.0.0.0.Beta2.Dotnet4.7.x64\Apps\MKVToolNix\mkvextract.exe D:\Video\---\---.mkv chapters D:\Video\---\---_temp\---_chapters.txt --simple

File 'D:\Video\---\---.mkv': container: Matroska
Track ID 0: video (MPEG-H/HEVC/h.265)
Track ID 1: audio (DTS-HD Master Audio)
Track ID 2: audio (DTS-HD Master Audio)
Track ID 3: subtitles (SubRip/SRT)
Track ID 4: subtitles (VobSub)
Track ID 5: subtitles (HDMV PGS)
Track ID 6: subtitles (VobSub)
Track ID 7: subtitles (HDMV PGS)
Track ID 8: subtitles (VobSub)
Track ID 9: subtitles (HDMV PGS)
Chapters: 20 entries

Start:    21:03:25
End:      21:03:25
Duration: 00:00:00

----------------------- Indexing using ffmsindex -----------------------

C:\StaxRip-2.0.0.0.Beta2.Dotnet4.7.x64\Apps\Plugins\both\ffms2\ffmsindex.exe D:\Video\---\---.mkv D:\Video\---\---_temp\---.ffindex

Writing index... done.

Start:    21:03:25
End:      21:04:02
Duration: 00:00:36

----------------- Extract forced subtitles if existing -----------------

C:\StaxRip-2.0.0.0.Beta2.Dotnet4.7.x64\Apps\BDSup2Sub++\bdsup2sub++.exe --forced-only -o "D:\Video\---\---_temp\--- ID7 German_forced.idx" "D:\Video\---\---_temp\--- ID7 German.idx"

--- ID7 German.idx

BDSup2Sub++ 1.0.2
OPTION: Exporting only forced subtitles.
Converting SUB/IDX
Loading D:/Video/---/---_temp/--- ID7 German.idx
Detected 0 forced captions.
No forced subtitles found.

Start:    21:04:39
End:      21:04:42
Duration: 00:00:02

----------------- Extract forced subtitles if existing -----------------

C:\StaxRip-2.0.0.0.Beta2.Dotnet4.7.x64\Apps\BDSup2Sub++\bdsup2sub++.exe --forced-only -o "---_temp\--- ID9 English_forced.idx" "---_temp\--- ID9 English.idx"

--- ID9 English.idx

BDSup2Sub++ 1.0.2
OPTION: Exporting only forced subtitles.
Converting SUB/IDX
Loading D:/Video/---/---_temp/--- ID9 English.idx
Detected 0 forced captions.
No forced subtitles found.

Start:    21:04:42
End:      21:04:43
Duration: 00:00:00`

**Comment by fmohican** [comment]
ughm i don't know if it's normal...
![TaskManager](https://i.imgur.com/1h52q1S.png)

**Comment by Revan654** [comment]
> Currently i can't provide much in here, StaxRip closes after the inital source import, never comes back froim import, nor displays any error or anything else.
But as you can see on my Screenshot, it's clearly StaxRip GUI which eats up the RAM and not the encoder.
To get it compileing i have imported the source via SaxRip 1.8.2.0 and than opened the saved project in StaxRip 2.0.0.0 Beta 2, since it force closes on import. The same happens on the 2.0.0.0 Stable (without Beta).
Should i open another issue for the import thing?
Btw. the same happens after StaxRip finishes thes encoding und muxing...mkv is finished, but StaxRip never comes back and force closes.

Anyway, here is the import source log, nothing special in here...no errors shown (I removed the source paths, as they're not important).

if the file isn't even opening completely then there something else going on creating the issue. It sounds like a registry key or FrameServer isn't completely installed. I know this happens with vapoursynth and python search path gets messed up.

I would make sure you have the correct dotnet installed along with AVS+ and if your using VS. VapourSynth R45 & Python 3.7.1.

**Comment by darkman1983** [comment]
I'm using Avisynth, Vapoursynth is not installed.
![2018-11-19 01_45_44-window](https://user-images.githubusercontent.com/553212/48680604-028d2f00-eb9d-11e8-8b14-c52dfe8f28bb.png)

The only thing that's interfering with anything StaxRip related is eg. K-Lite Codec Pack?!

**Comment by Revan654** [comment]
> 
> 
> I'm using Avisynth, Vapoursynth is not installed.
> ![2018-11-19 01_45_44-window](https://user-images.githubusercontent.com/553212/48680604-028d2f00-eb9d-11e8-8b14-c52dfe8f28bb.png)
> 
> The only thing that's interfering with anything StaxRip related is eg. K-Lite Codec Pack?!
> But isn't StaxRip only using all those libs and Apps located in it's own Apps folder?

No, Since ti requires usage of Framework, runtimes that .net Apps requires to run an .exe file

StaxRip Uses: App Folder, AVS+ dlls/Registry Key, dotnet Framework, Runtimes + dll that are next to exe file.

**Comment by darkman1983** [comment]
I've also checked Dotnet and all is okay there.

**Comment by Revan654** [comment]
Which Dotnet? For Which Arch?
