### ISSUE TITLE
A suggestion about releasing multiple-versions.

### ISSUE THREAD

**Issue by iAM261917** [Revan654/staxrip#45]
WinRAR has a feature called "Save identical files as references". It means that if two or more versions have a lot of identical files, you can just pack them in a same .rar package, and will not make the file size increase rapidly.
![qq 20181118151725](https://user-images.githubusercontent.com/42721712/48669709-1311bb00-eb45-11e8-867b-48045796fae3.png)
_why am i suggest this? because i wanted to try both of 2.0.0.0 beta2 versions, sadly i had to download excess contents._

**Comment by Revan654** [comment]
200 Megs is tiny, There are a few files that are different even if you don't notice them.
