### ISSUE TITLE
StaxRip 2.0.0.0 Beta 2 DotNet 4.7 - No VUI is imported

### ISSUE THREAD

**Issue by darkman1983** [Revan654/staxrip#46]
Just load a source and let it be processed until the GUI shows up.
If i go to encoder settings eg. for NVEnc, than on VUI tab all fields are undefined.

Screenshots is on the way, but i think it's clear enough.

Video Info for source:
```
ID                                : 1
Format                            : HEVC
Format/Info                       : High Efficiency Video Coding
Commercial name                   : HDR10
Format profile                    : Main 10@L5.1@High
Codec ID                          : V_MPEGH/ISO/HEVC
Duration                          : 1 h 46 min
Bit rate                          : 64.0 Mb/s
Width                             : 3 840 pixels
Height                            : 2 160 pixels
Display aspect ratio              : 16:9
Frame rate mode                   : Constant
Frame rate                        : 23.976 (24000/1001) FPS
Color space                       : YUV
Chroma subsampling                : 4:2:0 (Type 2)
Bit depth                         : 10 bits
Bits/(Pixel*Frame)                : 0.322
Stream size                       : 47.7 GiB (89%)
Default                           : Yes
Forced                            : No
Color range                       : Limited
Color primaries                   : BT.2020
Transfer characteristics          : PQ
Matrix coefficients               : BT.2020 non-constant
Mastering display color primaries : Display P3
Mastering display luminance       : min: 0.0050 cd/m2, max: 1000 cd/m2
Maximum Content Light Level       : 1000 cd/m2
Maximum Frame-Average Light Level : 221 cd/m2
```

**Comment by Revan654** [comment]
What ColorSpace are you importing?

**Comment by darkman1983** [comment]
Added Source Information to first post

**Comment by Revan654** [comment]
![untitled](https://user-images.githubusercontent.com/38091898/48679984-65ae9f80-eb64-11e8-9fb6-28cd9f691180.png)

It works & others are reporting it works with all the new added colorspaces, It's likely tied to your other issue. VUI import function is only read during opening the source file for the first time. How the VUI reads the data in 2.0 to 1.7 are very different. No to mention many of the encoding switches did not exist in 1.7 Specially on GPU Encoders.

**Comment by darkman1983** [comment]
I agree on that it's all different. But i have 10+ sources and on all sources it's the same Symptom.
