### ISSUE TITLE
Program collapse when trying to use QSVenc

### ISSUE THREAD

**Issue by iAM261917** [Revan654/staxrip#47]

**Comment by iAM261917** [comment]
Sorry, I made a mistake, I forgot the descripition.
So, you see, I chose QSVenc and then trying to open Ecoder Options window, then got an error.(both in avs and vs environment)
![default](https://user-images.githubusercontent.com/42721712/48675979-1d5ea400-eb9b-11e8-88a1-4209dc25352b.png)

The log file is here:
p.s. "在" = in

-------------------------- System Environment --------------------------

StaxRip    : 2.0
Windows    : Windows 10 Home 1803
Language   : Chinese (Simplified, China)
CPU        : Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
GPU        : Intel(R) HD Graphics 630, NVIDIA GeForce GTX 1050
Resolution : 1920 x 1080
DPI        : 96

------------------------------ Exception ------------------------------

System.Exception: key found twice: --pic-struct
   在 StaxRip.CommandLineForm..ctor(CommandLineParams params)
   在 StaxRip.QSVEnc.ShowConfigDialog()
   在 System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   在 System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   在 System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   在 System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ToolStrip.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by iAM261917** [comment]
Oh, sorry, it's midnight in China, I'm a little messed up.

**Comment by Revan654** [comment]
It will be addressed in the Final Release, Not sure why VS didn't catch that.
