### ISSUE TITLE
Forceclose on import of source if Crop Filter on AVS Filters is selected

### ISSUE THREAD

**Issue by darkman1983** [Revan654/staxrip#49]
```
-------------------------- System Environment --------------------------
StaxRip    : 2.0 Beta 2 NET 4.7
Windows    : Windows 10 Pro 1803
Language   : German (Germany)
CPU        : AMD Ryzen Threadripper 2950X 16-Core Processor
GPU        : NVIDIA GeForce GTX 1050 Ti
Resolution : 1920 x 1200
DPI        : 96
-----------------------------------------------------------------------------
```
If CROP Filter in AVS Filters is selected StaxRip closes without any error on importing source.
![2018-11-20 00_28_55-avs_filters](https://user-images.githubusercontent.com/553212/48741587-f6b47200-ec5b-11e8-9c60-cb2d115dd35e.png)
If i disable that switch, importing source is fine, i can also enable it after importing the source and crop without any problems.
I would like to provide a debug log, but the debug switch seems to do nothing, can't find any new log file in any folder.
![2018-11-20 00_27_43-settings](https://user-images.githubusercontent.com/553212/48741689-4c891a00-ec5c-11e8-89fe-c479f7f40dad.png)

**Comment by Revan654** [comment]
>  and crop

Debug logger is a listener for the Encoders.

I suggest fixing all your other issues first, That's where all your issues are located at.

Trying to use two different Versions with two different Setting keys & Switches is not going to work.

**Comment by darkman1983** [comment]
Closing all my Issues isn't fixing anything.
I can confirm, that all the other issues that i had, came from this one.
As all works fine with the described procedure.
I think you mixed this one with the other issues, because i've not used different versions.

And please stop closing my issues after one day, this is not enough time to answer, this is rediculous!

**Comment by Revan654** [comment]
Not sure your understanding what I'm saying or it's a Language barrier problem. Since it's unclear whats going on. It might try a forum that speaks your Language Since something is getting lost in translation. 

Automation System Closes the Issues after inactive after X amount of Time.
