### ISSUE TITLE
Same error check for updates showing error!

### ISSUE THREAD

**Issue by Cyberavater** [Revan654/staxrip#50]
Describe the bug or Issue

The system cannot find the file specified

File: D:\Portable

Arguments: Software\StaxRip\Update.bat

InvalidOperationException (2.0)

No process is associated with this object.

System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForExit(Int32 milliseconds)
   at StaxRip.Proc.Start()
   at StaxRip.GlobalCommands.ExecuteCommandLine(String commandLines, Boolean waitForExit, Boolean showProcessWindow, Boolean asBatch)

Step To Reproduce the Problem

Go to 'Advanced'
Click on 'Update'

Screenshots
https://imgur.com/a/ciryISz

Desktop (please complete the following information):

OS: [Windows 10 Build 1803]
Version [2.0]
Additional context
I updated to latest 2.0 beta2 but I still get this error

**Comment by Revan654** [comment]
Do you have Python using the Correct Search Path or Have Python installed?

File Structure Can Not be Altered in any ways.

Apps -> Update

**Comment by Cyberavater** [comment]
Do you have Python using the Correct Search Path or Have Python installed? >I Have Python installed.

**Comment by Revan654** [comment]
Having Python Installed and having it point to the proper Path are two very different things.

I know there are a few comments in the Source code saying there issues with dotnet apps being used from the D Drive.

You can Try to use this Version: https://www.anaconda.com/download/

Everything is running perfectly at my end, I have not heard anyone else saying there having issues with the script. It has to be something with the python path and the D Drive.

Two different coding and still having issues, Seems the issue is somewhere at your end.

FYI, StaxRip isn't designed to be portable.

**Comment by Cyberavater** [comment]
Okay, I'll try python from anaconda and then report U back..

**Comment by Cyberavater** [comment]
FYI, StaxRip isn't designed to be portable.> I just putted it in a folder named portable, if there was some external software that needed installation I installed it. But I couldn't install staxrip, could I?

**Comment by Cyberavater** [comment]
Having Python Installed and having it point to the proper Path are two very different things.> How can I have it point to the proper Path?

**Comment by Cyberavater** [comment]
Just for Testing Move it to the Desktop and try to Run it, The Script Can only Run directly from StaxRip.> I already did that!

**Comment by Cyberavater** [comment]
You can Try to use this Version: https://www.anaconda.com/download/

>This didn't worked...

**Comment by Cyberavater** [comment]
make sure Python runs to the VS Scripts & the Registry Keys are Properly valued.
>Registry Keys were Properly valued

**Comment by Cyberavater** [comment]
Suppose, It is User Issue as U just said there is no way it could be wrong in both of my PC...

**Comment by Cyberavater** [comment]
Why so hasty to close issues? Can't U wait like a week or smth?

**Comment by Revan654** [comment]
Not a StaxRip issue but a Python issue / Search Path issue, Only StaxRip bugs remain open. It's a better idea to take these type of questions to the Forums since you will get more help there.

**Comment by Cyberavater** [comment]
I see...
