### ISSUE TITLE
add hdragc

### ISSUE THREAD

**Issue by ABDOELSHEMY** [Revan654/staxrip#51]
hi @Revan654 
thank you very much for your hard work on staxrip
any chance to add ( hdragc ) filter to staxrip please

**Comment by Revan654** [comment]
> 
> 
> hi @Revan654
> thank you very much for your hard work on staxrip
> any chance to add ( hdragc ) filter to staxrip please

hdragc is a 32Bit Filter, All the other Filters are 64 Bit. You can not Mix different arch types together.

I know someone was trying to port it to 64Bit, but so far he hasn't had much luck, Mainly since the filter is closed source and it's missing a bunch of the source code.

**Comment by ABDOELSHEMY** [comment]
ah, i don't know how i forget that ( hdragc ) is an 32Bit Filter only, sorry for this a naïve question,  i can close this now

**Comment by Revan654** [comment]
I would follow this Thread: https://forum.doom9.org/showthread.php?t=93571&page=12

Since Coder is trying to get the filter up and running with StaxRip.

It might be awhile before anything happens.

The biggest issue is the code was always closed source, unlike most of the other filters which are open source.

**Comment by ABDOELSHEMY** [comment]
yeah, Unfortunately paviko is keep his great filter closed source, and after all this years there is no avisynth alternative for it
but it is a good news that there is someone trying to make an x64 version, I wish him success, and we finally have an x64 ( hdragc)
I will keep my eyes on this Thread to: https://forum.doom9.org/showthread.php?t=93571&page=12
much thanks for you time and effort @Revan654

**Comment by ABDOELSHEMY** [comment]
yeah, Unfortunately paviko is keep his great filter closed source, and after all this years there is no avisynth alternative for it
but it is a good news that there is someone trying to make an x64 version, I wish him success, and we finally have an x64 ( hdragc)
I will keep my eyes on this Thread to: https://forum.doom9.org/showthread.php?t=93571&page=12
much thanks for your time and effort @Revan654
