### ISSUE TITLE
Script error: there is no function named 'SetMTMode'

### ISSUE THREAD

**Issue by YinnVI** [Revan654/staxrip#52]
![image](https://user-images.githubusercontent.com/26527969/49658740-5ccf3080-fa75-11e8-8135-7b2072a19fc9.png)
![image](https://user-images.githubusercontent.com/26527969/49658890-a455bc80-fa75-11e8-83fb-93878a5043f4.png)

@Revan654 How to fix it?

**Comment by bandicootdancing** [comment]
I have that same problem. Tested on all releases and I get the same error.

**Comment by Revan654** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/26527969/49658740-5ccf3080-fa75-11e8-8135-7b2072a19fc9.png)
> ![image](https://user-images.githubusercontent.com/26527969/49658890-a455bc80-fa75-11e8-83fb-93878a5043f4.png)
> 
> @Revan654 How to fix it?

you need to use SetFilterMTMode. The Syntax in the screen is for AVS 2.6. Allot of these functions for MT are no longer needed since AVS+ Enables most of MT Functions by it self if the filter is newer.
