### ISSUE TITLE
Platform returned code 126 when enabling QTGMC

### ISSUE THREAD

**Issue by bandicootdancing** [Revan654/staxrip#53]
**Describe the bug or Issue**
Getting a script error when enabling QTGMC. "Platform returned code 126: The specified module could not be found." and "Cannot load file "C/Users/username/Downloads/1.9.0.0.x64/Apps/Plugins/AVS/EEDI3/eedi3.dll." If I go to that directory there is indeed a file named eedi3.dll so not sure what's going on. I do see issue #13 but that means nothing to me so far as the eedi3.dll file is sitting exactly where the program is expecting it. If it's a permissions issue I'll need some instruction.

I've deleted and extracted and set it to the alternate APPDATA location and it doesn't work there. 

I recently rebuilt my computer. The program semi worked on an old Windows 7 install although I couldn't get multi threading to work. I see another open issue for it here. It appears all Microsoft dependencies are installed under Apps>Manage. 

**Step To Reproduce the Problem**

1. Go to 'AVS Filters'
2. Click on 'Field radio button (default appears to be QTGMC'
3. Using 'x264' Encoder
4. 'Avisynth 
6. Trying to get QTGMC to work
7. Doesn't matter which file

**Desktop (please complete the following information):**
 - OS: Fresh install of Windows 10. A test Windows 7 VM came up with the same error except it said KNLMeansCL could not be found.
- Version All version. I tested every one
- Avisynth
- QTGMC (trying to get it to work)

**Comment by Revan654** [comment]
KNLMeansCL - OpenCL, Your GPU doesn't support it if you get an error.

eedi3 has a few different builds, The Default used is AVX. if it's an issue with eedi3 then your CPU doesn't support the default version.

**Comment by bandicootdancing** [comment]
Thanks for the pointer.

Using the version found [here](https://forum.doom9.org/showthread.php?t=172414) at doom9 did the trick with a 9900K.

**Comment by Revan654** [comment]
> 9900K

It seems the CPU has AVX2 but Limited support for the other Vectors including Backwards compatibility. No AVX512 Either. 

i9 are in a Strange Area when it comes to CPU's with Intel Brand.
