### ISSUE TITLE
How do I add new filters?

### ISSUE THREAD

**Issue by imPRAGMA** [Revan654/staxrip#54]
I have a plugin called Bifrost that I want to have working?
I put the .dll into /Plugins folder as /Plugins/Bifrost/libbifrost.dll and reopened Stax and theres absolutely no difference

**Comment by Revan654** [comment]
Adding to the Default list that has autodetect function can only be done through the source code.

You can manually add it to Filter list, Filters -> Profile. The dll loading line must be included as well.
