### ISSUE TITLE
x265 animation tuner

### ISSUE THREAD

**Issue by Aidolii** [Revan654/staxrip#55]
Just so you know, x265's nightlies have added a new animation tuner, pointed out in the documentation here: https://x265.readthedocs.io/en/default/presets.html

```
Animation
--tune animation adjusts encoder settings to optimize the encode quality for
animation content without impacting the encode speed. This is done by:

--psy-rd 0.4
--aq-strength 0.4
--deblock 1:1
--bframes Increase by 2
```

It might be worth including the x265 nightly in the upcoming 2.0 release.

...which I'm very excited for, by the way. How much longer must I wait? :(

**Comment by Revan654** [comment]
> u know, x265's nighties have added a new animation tuner, pointed out in the documentation

The Docs are missing some content.

There function Built into the source code that reads the encoder and list anything new and if anything been removed.
