### ISSUE TITLE
Intel H.265 Error

### ISSUE THREAD

**Issue by Aidolii** [Revan654/staxrip#56]
On the 2.0.0 beta 2 version, I had this error pop up when I attempted to change the encoder to Intel H.265:

```
NullReferenceException (2.0)

Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.QSVEnc.EncoderParams.OnValueChanged(CommandLineParam item)
   at StaxRip.BasicVideoEncoder.ImportCommandLine(String commandLine, CommandLineParams params)
```

If I try to encode the video despite this error popping up, I get this error and then the program crashes and opens my browser to this issue page:

```
NullReferenceException (2.0)

Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.QSVEnc.EncoderParams.OnValueChanged(CommandLineParam item)
   at StaxRip.QSVEnc.Encode()
   at StaxRip.GlobalClass.ProcessVideo()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath)
   at StaxRip.GlobalClass.ProcessJobs()
```

I'm on Windows 10 x64 October 2018 update and my favorite color is purple.

**Comment by Revan654** [comment]
The Key needs to be updated, It's already been fixed in the source code. VS failed notify me on that issue.

**Comment by Revan654** [comment]
> 
> 
> This error still happens with the latest version that I compiled yesterday. Unless you're saying you've fixed it on your end now that I've reported it.
> 
> In which case, I'd appreciate a commit, the last one was 5 days ago.

Make sure you have clean settings when running new version of the build. I have no idea when that last uploaded file was actually updated at my end. 

The Files that were compiled today worked when entering the encoder settings without any issue. I don't have a way to test QuickSync encoder.

**Comment by Aidolii** [comment]
The latest commit 15 hours ago has the updates, thank you.

**Comment by Revan654** [comment]
> 
> 
> The latest commit 15 hours ago has the updates, thank you.

Make sure you grab new Version, Since I only uploaded the Encoder files & none of the attached processes or files.
