### ISSUE TITLE
Hardcoded Subtitle Not Working

### ISSUE THREAD

**Issue by YinnVI** [Revan654/staxrip#57]
Hardcoded Subtitle Not Working fixit pls

**Comment by jalba69** [comment]
Hello,

might be similar issue as on old Staxrip version  : https://github.com/stax76/staxrip/issues/348 

replace the file "VSFilterMod.dll" located in" \Apps\Plugins\both\VSFilterMod\VSFilterMod.dll" by this version ( the x64 one inside VSFilterMod_bin.7z ) and give it a try, link to the newer version of the dll :

https://github.com/sorayuki/VSFilterMod/releases

**Comment by Revan654** [comment]
Have zero hard coded subtitle videos to test, your on your own on that.

**Comment by Revan654** [comment]
> 
> 
> Hello,
> 
> might be similar issue as on old Staxrip version : [stax76#348](https://github.com/stax76/staxrip/issues/348)
> 
> replace the file "VSFilterMod.dll" located in" \Apps\Plugins\both\VSFilterMod\VSFilterMod.dll" by this version ( the x64 one inside VSFilterMod_bin.7z ) and give it a try, link to the newer version of the dll :
> 
> https://github.com/sorayuki/VSFilterMod/releases

2.0 (Non-Beta) that was Release last night does provide that version.

**Comment by jalba69** [comment]
Hello Revan654,

good to know this dll is now bundled with the new release, it works way better than old version from 2016, as for the problem indeed it's hard to guess with no info's provided.

Thanks and happy new year ;).
