### ISSUE TITLE
There's something wrong with File Time.

### ISSUE THREAD

**Issue by iAM261917** [Revan654/staxrip#58]
Perhaps you forgot to include the "Modified" time in the release package, and it makes all apps "outdated".

**Comment by iAM261917** [comment]
![115 20181231165615](https://user-images.githubusercontent.com/42721712/50557141-15a72900-0d1d-11e9-976d-12e80020496a.png)
![115 20181231165634](https://user-images.githubusercontent.com/42721712/50557151-28b9f900-0d1d-11e9-8ec4-b36fefea7c3b.png)

**Comment by Revan654** [comment]
> 
> 
> Perhaps you forgot to include the "Modified" time in the release package, and it makes all apps "outdated".

anytime you update any file it has to be changed. Just make your text file matches the one provided. Just click version and hit enter.
