### ISSUE TITLE
intel H265---System.NullReferenceException: Object reference is not set to an instance of the object

### ISSUE THREAD

**Issue by Eziohawk** [Revan654/staxrip#62]
This is the first time I've submitted a question. I'm new here and would appreciate your guidance.
An error was reported with IntelH265 transcoding.

![snipaste_2019-01-06_03-40-37](https://user-images.githubusercontent.com/21170301/50728610-84deac00-1167-11e9-9da9-a00817145bbb.png)

![snipaste_2019-01-06_03-46-41](https://user-images.githubusercontent.com/21170301/50728616-b2c3f080-1167-11e9-8d74-42bf6633e59c.png)

[Error Reporting.log](https://github.com/Revan654/staxrip/files/2729848/Error.Reporting.log)

**Comment by Revan654** [comment]
It will be corrected in the next updated, I don't have access to QS system to fully debug the encoder.
