### ISSUE TITLE
Problem with Hardcoding subtitles with AviSynth

### ISSUE THREAD

**Issue by basuritashka** [Revan654/staxrip#63]
**Describe the bug or Issue**
Hardcoding subs with AviSynth (pure, no new dlls, nothing new) with an external subs (.ass) doesnt take certain styles properly (using crunchyroll subs) meanwhile using VapourSynth with core.sub.TextFile makes subtitles perfect.

Probably because it doesnt take PlayResX/Y properly

So I am wondering if there is a way to use core.sub.TextFile with AviSynth, because AviSynth is more fast than VapourSynth (with my own settings).

**Step To Reproduce the Problem**
1) Encode a .mkv via Avisynth, hardcode a crunchyroll .ass subs on it. voila
2) Compare it with a VapourSynth MKV video using the same hardcoded subtitles.

**Screenshots**
Original V4+ styles from a Crunchyroll sub:

![image](https://user-images.githubusercontent.com/33007491/50857238-cb9cf380-136b-11e9-9e3e-b323c7dc8651.png)

VapourSynth encoded making perfect subtitles:

![image](https://user-images.githubusercontent.com/33007491/50857431-5e3d9280-136c-11e9-821f-fbd54f0f6b31.png)

AviSynth makes it looks like a plain text:

![image](https://user-images.githubusercontent.com/33007491/50857559-c7250a80-136c-11e9-9073-52de732ce7fd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - OS Build: 17134.472 - Version: 1803
- Version: 2.0 StaxRip (?
- FrameServer Being Used [e.g. Avisynth]: Avisynth
- Version of External Application / Filter Being Used [e.g. 2.9+10]
- List of Filters Being Used [e.g. QTGMC]: DGSource
- Post your Logs, There Tell contain Allot of Information that Could Help.
- The More Information Posted, The Easier it will be to Debug.

**Additional context**
Using VapourSynth with core.sub.TextFile makes subtitles perfect.

**Comment by iAM261917** [comment]
Try to add this: "ScaledBorderAndShadow: yes" in where Playres been defined, and go on with your tests.

**Comment by iAM261917** [comment]
Like this:
![qq 20190110231804](https://user-images.githubusercontent.com/42721712/50977798-ff277b80-152d-11e9-8539-09461b52c88a.png)

**Comment by basuritashka** [comment]
Looks like that fixed it, not sure why, appreciated! (VapourSynth fix it without that parameter)
