### ISSUE TITLE
"Encoding settings" not being muxed to container

### ISSUE THREAD

**Issue by imPRAGMA** [Revan654/staxrip#65]
Is it possible to get this data like with Handbrakes H.264 (x265) codec?
For example:
`Encoding settings: cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=5102 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00`

I could manually do some of these but was wondering if theres some option to automatically do it.

**Comment by Revan654** [comment]
> 
> 
> Is it possible to get this data like with Handbrakes H.264 (x265) codec?
> For example:
> `Encoding settings: cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=5102 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:1.00`
> 
> I could manually do some of these but was wondering if theres some option to automatically do it.

It's part of the --info Flag, It's also completely useless for the end user.  It's basically nothing more then debug code left in the header.

That data does transfer over when using containers like mkv.

**Comment by imPRAGMA** [comment]
Right but I want to have it, how can I use this --info flag?

**Comment by mofortin** [comment]
to display encoding info : --info
to hide encoding info : --no-info

**Comment by Revan654** [comment]
> 
> 
> Right but I want to have it, how can I use this --info flag?

It's under bitstream and it's enabled by default.

**Comment by imPRAGMA** [comment]
If its enabled by default why isnt it working for me? It doesnt show it and I havent used --no-info

**Comment by imPRAGMA** [comment]
Also I cant find "bitstream"?

**Comment by imPRAGMA** [comment]
https://i.imgur.com/3PRgKiN.png

**Comment by imPRAGMA** [comment]
Im using NVEnc, perhaps there was some confusion?

**Comment by Revan654** [comment]
> 
> 
> Im using NVEnc, perhaps there was some confusion?

NVEnc doesn't have one from what I recall. You need to use x265 to get data written from the encoder.

**Comment by imPRAGMA** [comment]
> > Im using NVEnc, perhaps there was some confusion?
> 
> NVEnc doesn't have one from what I recall. You need to use x265 to get data written from the encoder or tunnel the data through.

Aww that sucks, no way at all to get it cause CPU Encoding is slow af

**Comment by mofortin** [comment]
CPU encoding is indeed slow but it's way more effective... Even at preset ultra-fast, CPU encoding gives better quality and bitrate compare to NVEnc. And at ultra-fast, I bet you can at least encode a 25+ fps easy ( depending on your CPU of course ). And If you really need faster encoding, I still bet x264 gives better overall quality/bitrate ratio than NVEnc and it is less demanding than x265

**Comment by Revan654** [comment]
> 
> 
> > > Im using NVEnc, perhaps there was some confusion?
> > 
> > 
> > NVEnc doesn't have one from what I recall. You need to use x265 to get data written from the encoder or tunnel the data through.
> 
> Aww that sucks, no way at all to get it cause CPU Encoding is slow af

Do you want Speed or Quality? x265 will always produce better picture Quality. If you want a quick and dirty encode then NVENc will do the job. Plus NVEnc doesn't properly apply the avs/vs filters.

The Filesize with NVEnc is all over the place.

Best would be adding NVENc as a speed boost instead of encoder then channel it back to x265. The problem with speed boost is you will run into bottlenecking. Where the GPU waits on the CPU to finish it's job.
