### ISSUE TITLE
audio desync decoding aac

### ISSUE THREAD

**Issue by sibylantonioforanna** [Revan654/staxrip#67]
Hi,
I'm using the latest version of staxrip 2.0.0.0 and I've noticed that when I try to encode again an aac stream to a different format, the audio slowly becomes more and more desynced with the video stream.
Odds are it's a problem with ffmpeg, but I was wandering if maybe there's a workaround for this problem, like adding the "aresample" option of ffmpeg? or anyways if something can be done with staxrip as is now to dodge the problem.
Thanks.

**Comment by Revan654** [comment]
> 
> 
> Hi,
> I'm using the latest version of staxrip 2.0.0.0 and I've noticed that when I try to encode again an aac stream to a different format, the audio slowly becomes more and more desynced with the video stream.
> Odds are it's a problem with ffmpeg, but I was wandering if maybe there's a workaround for this problem, like adding the "aresample" option of ffmpeg? or anyways if something can be done with staxrip as is now to dodge the problem.
> Thanks.

ffmpeg can complain about certain audio types, That is beyond my control. If the stream uses DTS avoid ffmpeg at all cost.

you can adjust the delay. One of the filters can also create desync problems, you have to be careful on what filters being used.

You also try using a different decoder.

Also check the source filter, It can sometimes produce the wrong data, Like LSmash I noticed has thrown off some of my videos off. They were suppose to be 33 Mins but only reported 27 Mins. By Switching to ffms for example fixed that Problems.

There just allot of variables that can throw off the audio.
