### ISSUE TITLE
Request: Can you make staxrip workable with more than 2 audios?

### ISSUE THREAD

**Issue by Cyberavater** [Revan654/staxrip#68]
Staxrip works with max dual audio. Can U increase the limit so that I can work with video files that have more than 2 audios?

https://imgur.com/a/6jttPaZ

**Comment by Revan654** [comment]
> 
> 
> Staxrip works with max dual audio. Can U increase the limit so that I can work with video files that have more than 2 audios?
> 
> https://imgur.com/a/6jttPaZ

It already does.

Check the Container Options.

**Comment by Cyberavater** [comment]
I didn't mean that, I meant the output file can't have more than 2 audios even if the source file has more than 2 audios. Can you set the limit to same as the source file?

**Comment by Revan654** [comment]
> 
> 
> I didn't mean that I meant the output file can't have more than 2 audios even if the source file has more than 2 audios. Can you set the limit to same as the source file?

I know, You can set and encode source files to a given format before it get's output.

**Comment by Cyberavater** [comment]
Umm yes, but you can't set it to have more than 2 audios. (I'm not sure why you aren't getting me.) Anyhow, here is a sample source file, now encode it. The output file must have all the audio.
https://mega.nz/#!oY8ExQjQ!MO8gRM5ieKAL17Xpg1gZ6cU0Tk51E5Gt7WlYHqHSCng

**Comment by almanteka** [comment]
you can add all the audio files from the source "manually" using the container options, but i think you're looking for staxrip to add all the audo files from the source "automatically"

![staxaudio](https://user-images.githubusercontent.com/42816936/51782951-fd51e080-2107-11e9-996a-a8cd5517f7ca.jpg)

**Comment by Cyberavater** [comment]
> you can add all the audio files from the source or external "manually" using the container options, pressing the +Add button, but i think you're looking for staxrip to add all the audio files from the source "automatically"?

Yes, thanks for understanding, I was asking for the settings to be automatic because I encode a lot of files based on a template adding them manually seems like a useless endless job.

**Comment by Schattenspieler** [comment]
And it seems counterintuitive, to have the ability to have more than 2 tracks, but to not have them presented that way automatically, when opening the source. Or have the option of a dialogue, asking if you'ld want to add the oder tracks from the source, too. Something like that would be much more logical.

**Comment by Revan654** [comment]
> 
> 
> > you can add all the audio files from the source or external "manually" using the container options, pressing the +Add button, but i think you're looking for staxrip to add all the audio files from the source "automatically"?
> 
> Yes, thanks for understanding, I was asking for the settings to be automatic because I encode a lot of files based on a template adding them manually seems like a useless endless job.

Use the Event Command or Scripting. Both are designed to add to automation chain. The tools are all there. 

It also helps to actually read the documentation.
