### ISSUE TITLE
Cannot load a 32 bit DLL in 64 bit Avisynth: 'C:/Program Files/AviSynth+/plugins64+/ffms2.dll'.

### ISSUE THREAD

**Issue by Abu3safeer** [Revan654/staxrip#71]
Hello everyone, on my friend PC this message shows when he loads an mkv file
![image](https://user-images.githubusercontent.com/12091003/51717882-c7532480-2053-11e9-8a81-35dc92fcaf75.png)

This is the text:
```
Cannot load a 32 bit DLL in 64 bit Avisynth: 'C:/Program Files/AviSynth+/plugins64+/ffms2.dll'.

(D:\[HorribleSubs] Yakusoku no Neverland - 03 [1080p]_temp\[HorribleSubs] Yakusoku no Neverland - 03 [1080p]_new_source.avs, line 1)
```

This is the content of '[HorribleSubs] Yakusoku no Neverland - 03 [1080p]_new_source.avs'
```
LoadCPlugin("C:\Users\DDDD\Downloads\Compressed\Staxrip.2.0.0.0.x64\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("D:\[HorribleSubs] Yakusoku no Neverland - 03 [1080p].mkv", colorspace = "YV12", \
              cachefile = "D:\[HorribleSubs] Yakusoku no Neverland - 03 [1080p]_temp\[HorribleSubs] Yakusoku no Neverland - 03 [1080p].ffindex")
```

As you can see, it uses ffms2.dll from C:/Program Files, so I thought StaxRip uses the wrong file, so I checked settings, but the path looks fine.

![image](https://user-images.githubusercontent.com/12091003/51718028-62e49500-2054-11e9-8683-e76c61ecefee.png)

Path on the settings looks fine, and on the 'avs' file looks good, why does it use wrong path?

**Comment by Abu3safeer** [comment]
Never mind it, it turned out he didn't install all requirements. 
now it does not show any errors.

Sorry for that.

**Comment by Revan654** [comment]
32Bit is Not Support anyways, It hasn't been for many years. All the dlls are pure 64Bit.

Always make sure your using the proper ffms and it's named correctly. 

ffms2 = Uses LoadC Function(Require FFMS C Plugin)
ffm2k = Uses Normal Load Function(Can use the Default version)

**Comment by Abu3safeer** [comment]
My friend used to use megui and x264, it is his first time using StaxRip, sow there might be conflict between StaxRip and other apps, specially if the app uses PATH to retrieve locations.

**Comment by Revan654** [comment]
> 
> 
> My friend used to use megui and x264, it is his first time using StaxRip, sow there might be conflict between StaxRip and other apps, specially if the app uses PATH to retrieve locations.

The Filters are completely independent from any other software. The only files that may create conflict are the FrameServers(Usually Python + VapourSynth). Which needs to be installed locally on the PC.
