### ISSUE TITLE
Where can I ask for questions about using StaxRip while it is not an issue?

### ISSUE THREAD

**Issue by Abu3safeer** [Revan654/staxrip#72]
Hello everyone,
I want to know where should I ask question related to StaxRip, but they are not issues.

my question is simply how to apply this code:
```
Afx=directShowSource("file")
Insertsign(last,afx,0,0)
```

I made sure [Irrational-Encoding-Wizardry/fvsfunc](https://github.com/Irrational-Encoding-Wizardry/fvsfunc) is installed properly, but could not find where to add it.

I am new to encoding scene, and cant find much tutorials about it, and don't know what should I type to search for it.
I found tutorials about other software, but not StaxRip.

**Comment by Schattenspieler** [comment]
If you dobn't have any issues, just try the support thread over at doom9: https://forum.doom9.org/showthread.php?t=172068
Although Revan is not the TO and stax retired, the thread is still active and probably will be for quite some time.

**Comment by Abu3safeer** [comment]
I have seen Doom forum in some Google search results, didn't know it was this popular, do you have any other forum like it where I can learn more about encoding?

**Comment by Abu3safeer** [comment]
Looks like I will wait 5 days
![image](https://user-images.githubusercontent.com/12091003/51786133-6d488100-2171-11e9-8f5f-49eb9a622474.png)

**Comment by Schattenspieler** [comment]
doom9 is generally a good place to go, if you're asking about video stuff.

**Comment by Abu3safeer** [comment]
My knowledge about video staff is almost zero, I am from Format Factory crew 😛

**Comment by Abu3safeer** [comment]
Using this button?
![image](https://user-images.githubusercontent.com/12091003/51793893-c26bad80-21d8-11e9-9f4e-b91513b19214.png)

**Comment by Revan654** [comment]
> 
> 
> Using this button?
> ![image](https://user-images.githubusercontent.com/12091003/51793893-c26bad80-21d8-11e9-9f4e-b91513b19214.png)

No, The Text that Says AVS Filters.

**Comment by Abu3safeer** [comment]
![image](https://user-images.githubusercontent.com/12091003/51795369-11bed780-21f3-11e9-9431-f3add5ceb601.png)
![image](https://user-images.githubusercontent.com/12091003/51795370-1b483f80-21f3-11e9-8150-bec4c44574a3.png)

Here

**Comment by Abu3safeer** [comment]
I am sorry for bothering you here, only 3 days and I will be able to replay there
![image](https://user-images.githubusercontent.com/12091003/51813907-b7447a80-22c9-11e9-8e78-320e420b99d6.png)

**Comment by Revan654** [comment]
> 
> 
> I am sorry for bothering you here, only 3 days and I will be able to replay there
> ![image](https://user-images.githubusercontent.com/12091003/51813907-b7447a80-22c9-11e9-8e78-320e420b99d6.png)
> I won't post any questions here, I will wait until I am able to replay on doom9.org, until that stay safe.

Strange, you have to wait that long to post.

Best is just to use the tool and learn from that and read and searching online. It's how I learned to encode video.
