### ISSUE TITLE
FFTW is needed but not installed on fresh windows installation

### ISSUE THREAD

**Issue by bobdig** [Revan654/staxrip#74]
After Fresh install of Windows 10 and stax 2.0.0.0 - x64 the following error is shown when I try do load a videofile.
First it want's to install this:
[https://abload.de/img/capture1gtkqj.png](url)
Then this is happening:
[https://abload.de/image.php?img=capture41jct.png](url)

After that I installed python, I also copied the files to the windows directory manually, doesn't help.

Sry I am only a novice user of stax since the beginning, maybe this projects is aiming in an other direction these days. 

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1809]
- Version 2

**Comment by Revan654** [comment]
> 
> 
> After Fresh install of Windows 10 and stax 2.0.0.0 - x64 the following error is shown when I try do load a videofile.
> First it want's to install this:
> [https://abload.de/img/capture1gtkqj.png](url)
> Then this is happening:
> [https://abload.de/image.php?img=capture41jct.png](url)
> 
> After that I installed python, I also copied the files to the windows directory manually, doesn't help.
> 
> Sry I am only a novice user of stax since the beginning, maybe this projects is aiming in an other direction these days.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. Windows 10 Build 1809]
> 
>     * Version 2

FFTW is external plugin, They need to be place in your system folder, The Plugins can be found in Apps / Support Folder.

If your using the latest Pipeline build then you can have it to auto-install from the App Manger.

**Comment by bobdig** [comment]
> If your using the latest Pipeline build then you can have it to auto-install from the App Manger.

This is not working in 2.0.0.0, asked a friend and he had the same problem. Although I don't know what a Pipeline build is. Manually copying all the files to the folders helped in the end.

**Comment by Revan654** [comment]
> 
> 
> > If your using the latest Pipeline build then you can have it to auto-install from the App Manger.
> 
> This is not working in 2.0.0.0, asked a friend and he had the same problem. Although I don't know what a Pipeline build is. Manually copying all the files to the folders helped in the end.

Current Build is 2.0.0.1, Very likely your still using a Beta build. 

Pipeline site can be access from the front Page by click on the icon.

**Comment by bobdig** [comment]
Current Build on GitHub is 2.0.0.0, that on I grabbed a few days ago and installed it on a Fresh Version of Windows 10. 
Anyway, found your pipeline site on your doom9 thread and finally got that version which states 2.0.0.1 beta  and here it is fixed.

**Comment by Aidolii** [comment]
It would've been nice to link it @bobdig 

https://ci.appveyor.com/project/Revan654/staxrip/builds/21708759/artifacts

**Comment by bobdig** [comment]
> Anyway, found your pipeline site on your doom9 thread and finally got that version which states 2.0.0.1 beta and here it is fixed.
What is another problem, tried to use QTGMC, it shows a script error:
[https://abload.de/img/capturebbjx9.png](url)

**Comment by bobdig** [comment]
`x265 [info]: HEVC encoder version 2.9+34-17120cfb5c99
x265 [info]: build info [Windows][MSVC 1920][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2`

DirectX is current and everything installed...

**Comment by bobdig** [comment]
I have all C++ runtimes and like I said, every directX whatever they are called.

**Comment by Revan654** [comment]
> 
> 
> I have all C++ runtimes and like I said, every directX whatever they are called installed.
> 
> [![Bild capture9qkwt.png auf abload.de](https://camo.githubusercontent.com/6365dec3a60cf6c1284a5cb7fbbf9395490365cb/68747470733a2f2f61626c6f61642e64652f696d672f6361707475726539716b77742e706e67)](http://abload.de/image.php?img=capture9qkwt.png)

I don't see any 2015 Runtimes.

StaxRip Manger, It will tell you exactly if there installed or not.

**Comment by bobdig** [comment]
> I don't see any 2015 Runtimes.
> 
> StaxRip Manger, It will tell you exactly if there installed or not.
Does it? 
[![Bild capture76j3x.png auf abload.de](https://abload.de/img/capture76j3x.png)](http://abload.de/image.php?img=capture76j3x.png)
