### ISSUE TITLE
Staxrip no longer populates Master Display information for HDR content

### ISSUE THREAD

**Issue by jsdukeboy08** [Revan654/staxrip#75]
I am having the issue where the Master Display information isn't being imported for my HDR content.  I was hoping that there was a fix for this by now.  I rip all my own 4K movies and literally all of them show 
"mastering display color primaries: Display P3".  What am I to put in the Master Display box since it is not auto populated?  Is there a way I can get this information elsewhere or is there some kind of general information that I could put in there.  Otherwise how can I encode my movies as the way I understand it that box needs to be filled in.  Below is a picture of what I'm referencing as well as the mediainfo

![mediainfo](https://user-images.githubusercontent.com/10006864/51800106-441b0580-21f0-11e9-97ef-e1bda52b25d6.PNG)

![stax](https://user-images.githubusercontent.com/10006864/51800192-67928000-21f1-11e9-97fb-cd4fa7b716b1.PNG)

**Comment by Revan654** [comment]
> 
> 
> I am having the issue where the Master Display information isn't being imported for my HDR content. I was hoping that there was a fix for this by now. I rip all my own 4K movies and literally all of them show
> "mastering display color primaries: Display P3". What am I to put in the Master Display box since it is not auto populated? Is there a way I can get this information elsewhere or is there some kind of general information that I could put in there. Otherwise how can I encode my movies as the way I understand it that box needs to be filled in. Below is a picture of what I'm referencing as well as the mediainfo
> 
> ![mediainfo](https://user-images.githubusercontent.com/10006864/51800106-441b0580-21f0-11e9-97ef-e1bda52b25d6.PNG)
> 
> ![stax](https://user-images.githubusercontent.com/10006864/51800192-67928000-21f1-11e9-97fb-cd4fa7b716b1.PNG)

You settings must be Updated, to the latest version (2.0+). This has been fixed for some time. It also been reported by a few that it fully works with all HDR sources(From P3 Base to P3 DCI to Pure HDR.

> DCI-P3: G(13250,34500)B(7500,3000)R(34000,16000)WP(15700,17550)L(10000000,1)
> Display-P3: G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)
> BT.2020: G(8500,39850)B(6550,2300)R(35400,14600)WP(15635,16450)L(10000000,1) 

You are also missing a flag for two for HDR Encoding.

**Comment by jsdukeboy08** [comment]
I am using staxrip 2.0.0.0, that is the correct version yes? my I ask what other flags I am missing for HDR encoding.  Also when you say that it is fixed, do you mean that it should auto populate the information now? Lastly, those figures that you listed, are those examples or something that is a standard for the Display type, meaning for "Display-P3" all movies would work with G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)

Thanks

**Comment by Revan654** [comment]
> 
> 
> I am using staxrip 2.0.0.0, that is the correct version yes? my I ask what other flags I am missing for HDR encoding. Also when you say that it is fixed, do you mean that it should auto populate the information now? Lastly, those figures that you listed, are those examples or something that is a standard for the Display type, meaning for "Display-P3" all movies would work with G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)
> 
> Thanks

Only Movies that are P3 would work with P3. These also P3-DCI so you have to be careful. 

Display-P3 Color is the same no matter what, it's a standard. Still not sure why Studio keep using P3 instead of the standard BT.2020 across the board.

This is the Bare Minimal for HDR:

-no-open-gop
-hdr
-aud
-hrd
-repeat-headers
-Matrix BT.2020 NC
-transfer ST.2084
-prime BT.2020
-Master-Color-Display (Must set value to Source color)
-Range limited (Only if your TV does Not Support Full or the Source is limited, You can also convert it to Full if you wish)
-MaxFall/CLL
-10Bit(HDR starts at 10bits)
-Profile Main10
-vui-hrd-info(Becomes Enabled with HRD Enabled)
-vui-timing-info

+ Ingest(Options need to be enabled in Options). (It's under Video).

All the Above Plus The Following is What I use:

These are based off of two-pass encoding:

--limit-refs 1 
--cu-lossless 
--aq-mode 1 (This was Changed recently, It why it's on the list now)
--pmode 
--pme 
--no-info 
--no-deblock 
--no-sao 
--psy-rd 1 
--no-strong-intra-smoothing

You Can also enable 

--no-slow-firstpass (it's up to you, I do 2 pass encoding for all my videos, CRF just gives you to large of a range and bitrate is all over the place.). It will tweak some of the settings and speed up the encoding.

There been a few 2.0 (Beta 1 & Beta 2) Then Final.

Current Build is: 2.0.0.1 Which can be obtained from the Pipeline.

**Comment by jsdukeboy08** [comment]
Awesome thanks for all that information it is of tremendous help, I will enable the flags that you have pointed out and also just so I am absolutely clear, when mediainfo shows exactly like the one that I have provided with “mastering display color primaries: Display P3” then the information to put in Master Display within staxrip is 

“G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)” 

Correct? 

Thank you again for all your help

**Comment by jsdukeboy08** [comment]
> > I am using staxrip 2.0.0.0, that is the correct version yes? my I ask what other flags I am missing for HDR encoding. Also when you say that it is fixed, do you mean that it should auto populate the information now? Lastly, those figures that you listed, are those examples or something that is a standard for the Display type, meaning for "Display-P3" all movies would work with G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)
> > Thanks
> 
> Only Movies that are P3 would work with P3. These also P3-DCI so you have to be careful.
> 
> Display-P3 Color is the same no matter what, it's a standard. Still not sure why Studio keep using P3 instead of the standard BT.2020 across the board.
> 
> This is the Bare Minimal for HDR:
> 
> -no-open-gop
> -hdr
> -aud
> -hrd
> -repeat-headers
> -Matrix BT.2020 NC
> -transfer ST.2084
> -prime BT.2020
> -Master-Color-Display (Must set value to Source color)
> -Range limited (Only if your TV does Not Support Full or the Source is limited, You can also convert it to Full if you wish)
> -MaxFall/CLL
> -10Bit(HDR starts at 10bits)
> -Profile Main10
> -vui-hrd-info(Becomes Enabled with HRD Enabled)
> -vui-timing-info
> 
> * Ingest(Options need to be enabled in Options). (It's under Video).
> 
> All the Above Plus The Following is What I use:
> 
> These are based off of two-pass encoding:
> 
> --limit-refs 1
> --cu-lossless
> --aq-mode 1 (This was Changed recently, It why it's on the list now)
> --pmode
> --pme
> --no-info
> --no-deblock
> --no-sao
> --psy-rd 1
> --no-strong-intra-smoothing
> 
> You Can also enable
> 
> --no-slow-firstpass (it's up to you, I do 2 pass encoding for all my videos, CRF just gives you to large of a range and bitrate is all over the place.). It will tweak some of the settings and speed up the encoding.
> 
> There been a few 2.0 (Beta 1 & Beta 2) Then Final.
> 
> Current Build is: 2.0.0.1 Which can be obtained from the Pipeline.

Awesome thanks for all that information it is of tremendous help, I will enable the flags that you have pointed out and also just so I am absolutely clear, when mediainfo shows exactly like the one that I have provided with “mastering display color primaries: Display P3” then the information to put in Master Display within staxrip is

“G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1)”

Correct?

Thank you again for all your help

**Comment by Revan654** [comment]
if MediaInfo says P3 then use P3, You can also use ffprobe to check as well. Not part of Staxrip.

**Comment by jsdukeboy08** [comment]
> if MediaInfo says P3 then use P3, You can also use ffprobe to check as well. Not part of Staxrip.

Awesome thank you again for all your help and for the development of this awesome software
