### ISSUE TITLE
Error Video encoding using x265 2.9+34 (2.0.0.0)

### ISSUE THREAD

**Issue by Cyberavater** [Revan654/staxrip#76]
Error Video encoding using x265 2.9+34 (2.0.0.0)

Video encoding using x265 2.9+34 failed with exit code: -1073741795 (0xC000001D)

The exit code might be a system error code: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.

------------------- Video encoding using x265 2.9+34 -------------------

"E:\Portable Software\StaxRip\Apps\Support\avs2pipemod\avs2pipemod64.exe" -y4mp "I:\Torrent\[DarkHollow] Little Busters! Refrain [BD 1080p DA-FLAC]\Creditless\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_temp\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_new.avs" | "E:\Portable Software\StaxRip\Apps\Encoders\x265\x265.exe" --crf 20 --output-depth 10 --colormatrix bt709 --frames 2183 --y4m --output "I:\Torrent\[DarkHollow] Little Busters! Refrain [BD 1080p DA-FLAC]\Creditless\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_temp\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_new_out.hevc" -

avs2pipemod[info]: writing 2183 frames of 24000/1001 fps, 1920x1080,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 2.360 sec.
avs2pipemod[error]: only wrote 0 of 2183 frames.

StaxRip.ErrorAbortException: Video encoding using x265 2.9+34 failed with exit code: -1073741795 (0xC000001D)

The exit code might be a system error code: {EXCEPTION}
Illegal Instruction
An attempt was made to execute an illegal instruction.

------------------- Video encoding using x265 2.9+34 -------------------

"E:\Portable Software\StaxRip\Apps\Support\avs2pipemod\avs2pipemod64.exe" -y4mp "I:\Torrent\[DarkHollow] Little Busters! Refrain [BD 1080p DA-FLAC]\Creditless\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_temp\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_new.avs" | "E:\Portable Software\StaxRip\Apps\Encoders\x265\x265.exe" --crf 20 --output-depth 10 --colormatrix bt709 --frames 2183 --y4m --output "I:\Torrent\[DarkHollow] Little Busters! Refrain [BD 1080p DA-FLAC]\Creditless\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_temp\[DarkHollow] Little Busters! Refrain NCOP [BD][x264,1080p,FLAC][10Bit][8E94BFA3]_new_out.hevc" -

avs2pipemod[info]: writing 2183 frames of 24000/1001 fps, 1920x1080,
sar 0:0, YUV-420-planar-8bit progressive video.
avs2pipemod[info]: finished, wrote 0 frames [0%].
avs2pipemod[info]: total elapsed time is 2.360 sec.
avs2pipemod[error]: only wrote 0 of 2183 frames.

   at StaxRip.Proc.Start()
   at StaxRip.x265Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority)
   at StaxRip.x265Enc.Encode()
   at StaxRip.GlobalClass.ProcessVideo()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath)

**Comment by Revan654** [comment]
1. 2.0 doesn't use 2.9 it Uses 3.0(Your Still using the Beta Build).
2. If your writing drive is portable, it possible it was asleep when trying to write to it.
3. Source filter could be the issue when trying to loading source into x265.
4. Be very careful with special characters, Windows tends throw out errors if it doesn't like one.
5. Make sure Long Path is Enabled.

**Comment by Cyberavater** [comment]
1. I'm using this one https://github.com/Revan654/staxrip/releases/download/2.0.0.0/Staxrip.2.0.0.0.x64.rar
2. I just named the folder portable it has nothing to do with being actually portable
3. Source filter was automatic.
4. There weren't any.
5. It's enabled
Bonus: I'm having this issue after 2.0.0.0 -62206a3 update. Staxrip was working fine with the previous beta release.

**Comment by Revan654** [comment]
> 
> 
>     1. I'm using this one https://github.com/Revan654/staxrip/releases/download/2.0.0.0/Staxrip.2.0.0.0.x64.rar
> 
>     2. I just named the folder portable it has nothing to do with being actually portable
> 
>     3. Source filter was automatic.
> 
>     4. There weren't any.
> 
>     5. It's enabled
>        Bonus: I'm having this issue after 2.0.0.0 -62206a3 update. Staxrip was working fine with the previous beta release.

1. I would double check to make sure it's the right one, I altered some of those files after the Release or just grab the Pipeline build.
2. Unless it's a SSD Drives or Main Drive, Some drives require time to boot-up.
3. Just because the Source is loaded doesn't mean an encoder will accepting the filter being used.
4. There allot just based on the log you posted.

It sounds like one of the files being used is not compatible with your CPU or it's having finding a dll.

**Comment by Cyberavater** [comment]
> 1. I would double check to make sure it's the right one, I altered some of those files after the Release or just grab the Pipeline build.
2. Unless it's a SSD Drives or Main Drive, Some drives require time to boot-up.
Just because the Source is loaded doesn't mean an encoder will accepting the filter being used.
3. There allot just based on the log you posted.
It sounds like one of the files being used is not compatible with your CPU or it's having finding a dll.

1. link plz
2. It's my main drive.
3. Ok... but I don't see user's fault here (It was there from automatic workflow).
4. I thought if I had special characters it won't even add the file which I experienced when I actually had special characters ("#$%).

Could be, but I can't add the dll if you don't name it.

**Comment by Revan654** [comment]
> 
> 
> > 1. I would double check to make sure it's the right one, I altered some of those files after the Release or just grab the Pipeline build.
> > 2. Unless it's a SSD Drives or Main Drive, Some drives require time to boot-up.
> > 3. Just because the Source is loaded doesn't mean an encoder will accepting the filter being used.
> > 4. There allot just based on the log you posted.
> >    It sounds like one of the files being used is not compatible with your CPU or it's having finding a dll.
> 
> 1̶̶̶.̶̶̶ ̶̶̶S̶̶̶u̶̶̶r̶̶̶e̶̶̶ ̶̶̶d̶̶̶o̶̶̶ ̶̶̶&̶̶̶ ̶̶̶l̶̶̶i̶̶̶n̶̶̶k̶̶̶ ̶̶̶p̶̶̶l̶̶̶z̶̶̶
> 2̶.̶ ̶I̶t̶'̶s̶ ̶m̶y̶ ̶m̶a̶i̶n̶ ̶d̶r̶i̶v̶e̶.̶
> ̶3̶.̶ ̶O̶k̶.̶.̶.̶ ̶b̶u̶t̶ ̶I̶ ̶d̶o̶n̶'̶t̶ ̶s̶e̶e̶ ̶u̶s̶e̶r̶'̶s̶ ̶f̶a̶u̶l̶t̶ ̶h̶e̶r̶e̶ ̶(̶I̶t̶ ̶w̶a̶s̶ ̶t̶h̶e̶r̶e̶ ̶f̶r̶o̶m̶ ̶a̶u̶t̶o̶m̶a̶t̶i̶c̶ ̶w̶o̶r̶k̶f̶l̶o̶w̶)̶.̶
> ̶4̶.̶ ̶I̶ ̶t̶h̶o̶u̶g̶h̶t̶ ̶i̶f̶ ̶I̶ ̶h̶a̶d̶ ̶s̶p̶e̶c̶i̶a̶l̶ ̶c̶h̶a̶r̶a̶c̶t̶e̶r̶s̶ ̶i̶t̶ ̶w̶o̶n̶'̶t̶ ̶e̶v̶e̶n̶ ̶a̶d̶d̶ ̶t̶h̶e̶ ̶f̶i̶l̶e̶ ̶(̶s̶a̶y̶i̶n̶g̶,̶ ̶a̶v̶s̶ ̶d̶o̶e̶s̶n̶'̶t̶ ̶s̶u̶p̶p̶o̶r̶t̶ ̶s̶p̶e̶c̶i̶a̶l̶ ̶c̶h̶a̶r̶a̶c̶t̶e̶r̶s̶ ̶s̶w̶i̶t̶c̶h̶ ̶t̶o̶ ̶V̶a̶p̶o̶u̶r̶s̶y̶n̶t̶h̶ ̶t̶o̶ ̶w̶o̶r̶k̶ ̶w̶i̶t̶h̶ ̶s̶p̶e̶c̶i̶a̶l̶ ̶c̶h̶a̶r̶a̶c̶t̶e̶r̶s̶)̶ ̶w̶h̶i̶c̶h̶ ̶I̶ ̶e̶x̶p̶e̶r̶i̶e̶n̶c̶e̶d̶ ̶w̶h̶e̶n̶ ̶I̶ ̶a̶c̶t̶u̶a̶l̶l̶y̶ ̶h̶a̶d̶ ̶s̶p̶e̶c̶i̶a̶l̶ ̶c̶h̶a̶r̶a̶c̶t̶e̶r̶s̶ ̶(̶"̶#̶$̶%̶？̶∕̶꞉̶)̶.̶
> ̶
> ̶C̶o̶u̶l̶d̶ ̶b̶e̶,̶ ̶b̶u̶t̶ ̶I̶ ̶c̶a̶n̶'̶t̶ ̶a̶d̶d̶ ̶t̶h̶e̶ ̶d̶l̶l̶ ̶i̶f̶ ̶y̶o̶u̶ ̶d̶o̶n̶'̶t̶ ̶n̶a̶m̶e̶ ̶i̶t̶.̶
> 
> Edit: Who am I kidding, you are wrong on the point # 1 no need to go through all the other points. (no offense plz)
> 
> > 1. 2.0 doesn't use 2.9 it Uses 3.0(Your Still using the Beta Build).
> 
> Check it, you'll see 2.0.0.0 -62206a3 uses "2.9" NOT "3.0" ( And of course, I'm not still using the beta build).

1. Front Page
2. C:\ is the Main Drive, All others are addon Drives.
3. Staxrip picks the best possible source file for the container, There are way to many variables to account for everything. Encoder, all the Encoder Flags that being used, The Source File, Filters and Frameserver. EX: x264 doesn't get along with ffms with certain settings.
4. I have no idea what dll you could missing, all that is based on your script and what needs to be loaded. 

Finally Make sure your using the Proper dll files designed for your CPU Vectors(Run x265.exe -V from the command like to get the readout).

EX: AVX CPU's will not be able to use AVX2 dll files.

The Latest Build is 2.0.0.1(Which uses 3.0+ Specs).
The 2.0 Final Release uses 2.9+34-17120cfb5c99 but can be easily updated.

**Comment by mofortin** [comment]
I've been using it for quite a while now and haven't had any issues. StaxRip is basically just a GUI for other CLI software. If one of those external software throws error ( because, most of the time, the end user doesn't properly understand how it works ), then it is not entirely StaxRip's fault.

**Comment by Revan654** [comment]
> 
> 
> All 2.xx versions of Stax have been throwing various exceptions and the dev continues to suggest bizarre fixes or causes.

There nothing bizarre with any answer, All these problems can be fixed from above answers. Not to mention MS even suggests some of these from there on docs while debugging.

Since this post is going no where. It's being Closed. Since OP seem to have left the topic.
