### ISSUE TITLE
NullReferenceException error  on intel QSV encoder!

### ISSUE THREAD

**Issue by woshilaiba** [Revan654/staxrip#79]
this issus is related to #60 #62 ,
I just want to show some clue on this issue.

1. There is no problem when use QVSEnc 3.17 with Staxrip 1.7 on windows10（version 1803 and 1809） ,but Staxrip2.0 not work and show "NullReferenceException" error.
Does not test whether working on windows7

2. In Staxrip2.0 there is no problem with ffmpeg-intel-h264 on windows10（version 1803 and 1809）

BTW, Staxrip2.0 is very good!

**Comment by Revan654** [comment]
Your still using an older build that's why. Update to one of the builds from the Pipeline(Link is on the front page).

**Comment by woshilaiba** [comment]
> 
> 
> Your still using an older build that's why. Update to one of the builds from the Pipeline(Link is on the front page).

Excuse me， but I use “2.0.0.0 - x64” which  you released on Dec 31, 2018 from https://github.com/Revan654/staxrip/releases
Is there other place to download a new build or should I build it from the latest source？
Thank you！

**Comment by mofortin** [comment]
https://ci.appveyor.com/project/Revan654/staxrip/build/artifacts

**Comment by Revan654** [comment]
> 
> 
> > Your still using an older build that's why. Update to one of the builds from the Pipeline(Link is on the front page).
> 
> Excuse me， but I use “2.0.0.0 - x64” which you released on Dec 31, 2018 from https://github.com/Revan654/staxrip/releases
> Is there other place to download a new build or should I build it from the latest source？
> Thank you！

The Icon on the Front Page that says Build Passing. Click on that, It will always contain the more Recent Code. Minus any external files.

**Comment by Eziohawk** [comment]
> Your still using an older build that's why. Update to one of the builds from the Pipeline(Link is on the front page).

I have the same question.I don't know how to download the beta software at all. 😭There's only 824KB of incremental updates？😂I'm just an ordinary netizen and I rarely log in to GitHub to download software, so I'm not as familiar with GitHub as developers. 
A lot of ordinary people can only download the Release version of the software. For example, a large complete package[Staxrip.2.0.0.1.x64.rar],that is great!😄
I see the changelog.md said x265 Has been updated to 3.0.Does x265 need to download updates manually?
Finally, thank you for your hard work. Happy Valentine's Day！❤

**Comment by Revan654** [comment]
> t an ordinary netizen and I rarely log in to GitHub to download software, so I'm not as familiar with GitHub as developers.

x265 3.0 has been added but you don't need to update x265 if you want to. Yes, It has to be downloaded manually.

-----

Pipeline is actually not part of Github but part of another service. It also makes things easier at my end and reduces the time required.

All your doing it overwriting the .exe file nothing more.

The Complete package takes allot longer to put together, since all the external resources have to be built(Which takes hours Since it has to go through each file and rebuild it from latest source code).
