### ISSUE TITLE
Cannot install FFTW

### ISSUE THREAD

**Issue by StoneboyCZ** [Revan654/staxrip#82]
When I try to install the FFTW plugin using the Tools Window, I get the following error: 

FFTW returned an error.

and nothing else. Am I doing something wrong? 
Version: 2.0.0.0 - x64
Windows 10 1809 x64

**Comment by silverspoonfrog** [comment]
I get the same thing so I went to http://www.fftw.org/install/windows.html
Put the DLL files from this zip ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll32.zip in C:\Windows\System32
Put the DLL files from this zip ftp://ftp.fftw.org/pub/fftw/fftw-3.3.5-dll64.zip in  C:\Windows\SysWOW64
Worked like a charm.

**Comment by StoneboyCZ** [comment]
Thank you so much, it works :).

**Comment by Revan654** [comment]
Your Still using Beta Release, Latest Version works and can always be Obtained from the Pipeline.
