### ISSUE TITLE
MPEG2Source - Can't Read the d2v File

### ISSUE THREAD

**Issue by imPRAGMA** [Revan654/staxrip#85]
When you try use MPEG2Source Source Filter, it will never load and always fail.
(This only occurs in 2.0.0.0, it doesnt happen with 1.9.0.0)

**Step To Reproduce the Problem**

1. Open Stax2.0 and set MPEG2Source as the Source filter (https://i.imgur.com/sBl8DiL.png)
2. Open up a MPEG file from a DVD into it (I went from DVD -> MPEG MKV file with MakeMKV) It will give you the error. (https://i.imgur.com/Omj8iaN.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1803] Windows 10 Build 1809
- Version [e.g. 1.9] 2.0
- FrameServer Being Used [e.g. Avisynth] AviSynth
- Version of External Application / Filter Being Used [e.g. 2.9+10] N/A
- List of Filters Being Used [e.g. QTGMC] N/A

**Comment by Revan654** [comment]
Not really a Staxrip problem but an issue in how DVD was extracted using MakeMKV or how MPEGSource reads the file. Both are external files.

**Comment by imPRAGMA** [comment]
The d2v file doesnt get extracted, its clearly an issue with 2.0.0.0 as I said it works in 1.9.0.0, do you even bother to test or verify your statements?

**Comment by Revan654** [comment]
> 
> 
> The d2v file doesnt get extracted, its clearly an issue with 2.0.0.0 as I said it works in 1.9.0.0, do you even bother to test or verify your statements?

Seem to be an issue at your end or your search path. This has not been reported by anyone else.

Yes, I already test it and works fine. 

No log has been provided nor any exit codes. This can not be re-produced.
