### ISSUE TITLE
What is the aim this time for a stable release?

### ISSUE THREAD

**Issue by pwacooijmans** [Revan654/staxrip#88]
Dear Revan654,

I am wondering when will we have another stable release and what is the aim for this stable release that we are going to?

Kind Regards,

Pieter Cooijmans

**Comment by Revan654** [comment]
I don't set dates for stable Releases, Many things can happen during development Which can delay updated code.

Most of the Code from Beta Release should be Stable. I just havn't had time to test everything that has been added.

**Comment by pwacooijmans** [comment]
Thx for the quick response I hope you can find time for a stable build in
the future. Furthermore v4.28 as you said yourself works fine without the
bit missing to close the nal sei.

Many thanks for your continued support on nvenc...love the program and you
made such steps in quality that it's really noticable.

Keep up the good work,

Kind regards,

Pieter Cooijmans

Op wo 13 mrt. 2019 22:27 schreef Revan654 <notifications@github.com>:
