### ISSUE TITLE
Quality difference between 1.7.0.0 stable and 2.0.0.1 why?

### ISSUE THREAD

**Issue by pwacooijmans** [Revan654/staxrip#89]
![Naamloos2](https://user-images.githubusercontent.com/30800180/54371293-6de19c00-4679-11e9-88a3-757b33676ff4.png)
![Naamloos3](https://user-images.githubusercontent.com/30800180/54371294-6de19c00-4679-11e9-98c8-6b009ef391e4.png)

Naamloos2 is made with stable version 1.7.0.0 from staxrip and nvenc 4.32
Naamloos3 is made with beta version 2.0.0.1 from staxrip and nvenc 4.32

Why is there such a big difference in quality?
The size of the file should be exactly simular, however it isn't even close to simular.
![Naamloos](https://user-images.githubusercontent.com/30800180/54371477-ba2cdc00-4679-11e9-8b54-a0b397157653.png)
This is the original.
To have some things to compare.

Was just wondering why 1.7.0.0 works at half the speed of 2.0.0.1 but has way better quality.

NVEncC64 --master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,1) --max-cll 1000,640 --sar %target_sar% --vbr 25000 --codec h265 --preset quality --output-depth 10 --lookahead 32 --output-buf 128 --cuda-schedule auto --no-b-adapt --no-i-adapt --videoformat pal --max-bitrate 40000 --vbv-bufsize 160000 --aq --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --mv-precision q-pel --chromaloc 2 -i "%script_file%" -o "%encoder_out_file%"

This was the string used.

and here you have a link to the 3 samples

https://drive.google.com/drive/folders/16I0JHWxabP7suokpuIau6khVd4e7DCzq?usp=sharing

Thx for taking the time to explain this.

Kind regards,

Pieter Cooijmans

**Comment by mofortin** [comment]
The version of StaxRip in itself has literally no effects on the encoding speed or the quality of the encode. If you are using the same version of NVENC with the same parameters, your issue may comes from your pre-processing script ( avisynth, vapoursynth, etc. )

**Comment by pwacooijmans** [comment]
LoadCPlugin("E:\Extra
Programs\Staxrip.2.0.0.1.Beta\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("C:\Push the Tempo\La La Land (2016) Untouched sample
Original sample.mkv", colorspace = "YV12", \
              cachefile = "C:\Push the Tempo\La La Land (2016) Untouched
sample Original sample_temp\La La Land (2016) Untouched sample Original
sample.ffindex")
this is version 2.0.0.1

and

LoadPlugin("E:\Extra
Programs\StaxRip-x64-1.7.0.0-stable\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("C:\Push the Tempo\La La Land (2016) Untouched sample
Original sample.mkv", colorspace = "YV12", \
              cachefile = "C:\Push the Tempo\La La Land (201..._temp\La La
Land (2016) Untouched sample Original sample.ffindex")
this is version 1.7.0.0

So what's the issue if there is no difference?

Many thanks for looking at this,

Kind Regards,

Pieter Cooijmans

Op do 14 mrt. 2019 om 17:35 schreef Marc-Olivier Fortin <
notifications@github.com>:

**Comment by pwacooijmans** [comment]
Do note that there is an api update on 4.32 which goes from 8.1 to 9.0
hopefully this will shed some light into it.

Kind Regards,

Pieter Cooijmans

Op do 14 mrt. 2019 om 18:25 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
1 Log file of version x.64.1.7.0.0 Stable and 1 Log file of version 2.0.0.1
beta.

Op do 14 mrt. 2019 om 18:27 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by pwacooijmans** [comment]
https://www.diffchecker.com/ is handy to check the differences in the log
files.

Op do 14 mrt. 2019 om 18:40 schreef Pieter Cooijmans <pwacooijmans@gmail.com

**Comment by mofortin** [comment]
Maybe try using the same DLL's ( ffms2.dll )

**Comment by pwacooijmans** [comment]
Ok I ripped the ffms2 completely from 1.7.0.0 and put it in 2.0.0.1 and now I have exactly the same results I used to have with 1.7.0.0 so issue seems fixed.....question remaining is what's the best version?
Is it 2.23.1 of the official github ffms or 2.30 from someone else?

Could you please share your thoughts on this?

Many Thanks,

Pieter Cooijmans

**Comment by pwacooijmans** [comment]
It's just for my knowledge 2.30 of ffms2, no clue where you got that from since the releases only go to 2.23.1

**Comment by mofortin** [comment]
That I don't know.. And since you are using NVENC you can use HW decode as well.. I'm pretty sure @Revan654 updated StaxRip for this.. ( probably in the options section of NVENC encoder --> https://staxrip2.readthedocs.io/en/latest/screenshots.html#nvenc, decoder: avisynth... ).

Another option would be to use DGIndexNV / DGDecNV which is also a GPU Accelerated Decoder but requires a licence ( I'm sure you can find one on internet though )

**Comment by mofortin** [comment]
2.30 might only be a typo... since in the doc it refers to the real repo

**Comment by pwacooijmans** [comment]
This is not the case, and here is the proof:
![Naamloos](https://user-images.githubusercontent.com/30800180/54384643-033e5980-4695-11e9-9bad-ac3266834de3.png)
![Naamloos2](https://user-images.githubusercontent.com/30800180/54384652-046f8680-4695-11e9-869e-6e1d2ed84d4f.png)

**Comment by mofortin** [comment]
If you look at the github page of FFMS2, the latest release was on October 2016. My guess is that @Revan654 compiled ( himself ) the latest code because there are still progress made in the source code but no new release yet.

**Comment by pwacooijmans** [comment]
ok thx for the info, no clue what to choose yet, I'll guess I'll just wait till @Revan654 comes with a decent version.

You can close this issue, many thanks for all the fast responses.

Kind Regards,

Pieter Cooijmans

**Comment by mofortin** [comment]
I cannot close this issue but you can :) I'm no admin here
