### ISSUE TITLE
x264 embedded avs doesn't support high bit depth

### ISSUE THREAD

**Issue by Funodav** [Revan654/staxrip#9]
Hello, when I'm using a 10 bits input (yuv420p10) or higher with x264 StaxRip isn't using the external avs2pipemod but reather use the internal x264 one, resulting in a crash (because >8bits isn't supported).

For x265 (and others) it's working flawlessly.
Please make it not use the internal one or make an option like in x265.

Best regards.

**Comment by Revan654** [comment]
x264 doesn't use the pipemod, only x265 and such runs through that software.  Double check and make sure your running r2801 and it's the 10bit version. 

x264 at 10Bits is supported. It sounds more like a filter issue then a codec/encoder issue.

**Comment by Funodav** [comment]
Yes, I didn't touch the executable it is the r2801
there is the error : 

Error Video encoding using x264 10-Bit 2801 (1.8.2.0)

Video encoding using x264 10-Bit 2801 failed with exit code: -1 (0xFFFFFFFF)


---------------- Video encoding using x264 10-Bit 2801 ----------------

C:\Users\;;;;;;;\Downloads\StaxRip-x64-1.8.2.0-test\Apps\x264\x264-10b.exe --crf 20 --output "C:\Users\;;;;;;\Downloads\JoJo no Kimyo n..._temp\JoJo no Kimyo na Boken - Diamond wa Kudakenai - 01 VOSTFR FHD H265_out.h264" "C:\Users\;;;;;;\Downloads\JoJo no Kimyo n..._temp\JoJo no Kimyo na Boken - Diamond wa Kudakenai - 01 VOSTFR FHD H265.avs"

avs [error]: not supported pixel type: YUV420P10
x264 [error]: could not open input file `C:\Users\;;;;;;\Downloads\JoJo no Kimyo n..._temp\JoJo no Kimyo na Boken - Diamond wa Kudakenai - 01 VOSTFR FHD H265.avs'



StaxRip.ErrorAbortException: Video encoding using x264 10-Bit 2801 failed with exit code: -1 (0xFFFFFFFF)


---------------- Video encoding using x264 10-Bit 2801 ----------------

C:\Users\;;;;;;;;;;\Downloads\StaxRip-x64-1.8.2.0-test\Apps\x264\x264-10b.exe --crf 20 --output "C:\Users\;;;;;;;;\Downloads\JoJo no Kimyo n..._temp\JoJo no Kimyo na Boken - Diamond wa Kudakenai - 01 VOSTFR FHD H265_out.h264" "C:\Users\;;;;;;;;;\Downloads\JoJo no Kimyo n..._temp\JoJo no Kimyo na Boken - Diamond wa Kudakenai - 01 VOSTFR FHD H265.avs"

avs [error]: not supported pixel type: YUV420P10
x264 [error]: could not open input file `C:\Users\,,,,,,,,,,,\Downloads\JoJo no Kimyo n..._temp\JoJo no Kimyo na Boken - Diamond wa Kudakenai - 01 VOSTFR FHD H265.avs'


   à StaxRip.Proc.Start()
   à StaxRip.x264Enc.Encode(String passName, String commandLine, ProcessPriorityClass priority)
   à StaxRip.x264Enc.Encode()
   à StaxRip.GlobalClass.ProcessVideo()
   à System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à StaxRip.GlobalClass.ProcessJob(String jobPath)

**Comment by Funodav** [comment]
Yes, I didn't touch the executable it is the r2801
there is the error :

Error Video encoding using x264 10-Bit 2801 (1.8.2.0)

Video encoding using x264 10-Bit 2801 failed with exit code: -1 (0xFFFFFFFF)

---------------- Video encoding using x264 10-Bit 2801 ----------------

C:\Users\;;;;;;;\Downloads\StaxRip-x64-1.8.2.0-test\Apps\x264\x264-10b.exe --crf 20 --output "C:\Users\;;;;;;\Downloads\test_temp\test_out.h264" "C:\Users\;;;;;;\Downloads\test_temp\test.avs"

avs [error]: not supported pixel type: YUV420P10
x264 [error]: could not open input file `C:\Users\;;;;;;\Downloads\test_temp\test.avs'

StaxRip.ErrorAbortException: Video encoding using x264 10-Bit 2801 failed with exit code: -1 (0xFFFFFFFF)

**Comment by Revan654** [comment]
That's not an issue with the encoder but the actual filter you use to open the video. Many source filters are just not designed for 10Bit. I would try another one and see if that works.  YUV420P10 has issues with many of the source filters. Even with my own personally recorded videos. try LSmash or ffms.

**Comment by Funodav** [comment]
I tried FFVideoSource, this is the avs file : Same error

LoadPlugin("C:\Users\David\Downloads\StaxRip-x64-1.8.2.0-test\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("C:\Users\David\Downloads\test.mp4", colorspace = "YUV420P10", \
              cachefile = "C:\Users\David\Downloads\test_temp\test.ffindex")

x265 (avs2pipemod) or any **encoder** under the ffmpeg list **don't** have this behavior/error with the same config.

**Comment by Revan654** [comment]
I've tried it a few times already. It just does not crash for 10b videos I load in. 

You are using an outdated binary for x264 for 10Bit. r2801 is not even part of the stable path. The latest stable release is r2851 which I included in the release.

link: https://download.videolan.org/pub/videolan/x264/binaries/win64/

I would also check to see if your encoder is using shared or static libs.

It's hard to debug from here, since there not allot of info to use to see whats going wrong.

**Comment by Funodav** [comment]
When you put a high bit depth video don't forget to change the colorspace in the source filter because it defaut to YUV420P8. 
I picked the latest 10b build but no same thing ...
This is the full log : https://pastebin.com/vXVJ78Ut

**Comment by Revan654** [comment]
FFVideoSource("C:\Users\User\Videos\codec test\Exodus_UHD_HDR_Exodus_draft.mp4", **colorspace = "YUV420P10"**, \

- by Default FFMS not support 10Bit formats, you need the 10Bit Hack.

You may also want to use reducerange=true for x264.

It will just depend on which FFMS your using since there are allot of different builds.

[img]https://i.imgur.com/C3G89Uc.jpg[/img]
[img]https://i.imgur.com/TTaTxhF.jpg[/img]
[img]https://i.imgur.com/9wplxyz.jpg[/img]

Remember when using FFMS with 10Bit+ it will get returned as a stack. Take that into consideration.

More info on FFMS & High Bit Depth:

Link: http://avisynth.nl/index.php/High_bit-depth_Support_with_Avisynth#Importing_High_Bit-depth_Video_into_AviSynth
Link: http://avisynth.nl/index.php/FFmpegSource

**Comment by Funodav** [comment]
Yeah, but staxrip uses avisynth+ and ffms2 :
https://github.com/FFMS/ffms2/releases
"Added support for high bitdepth output in Avisynth+"
so no need for stack16 it is natively suported (again avs2pipemod and ffmpeg when executing the avs script no error) :
ffmpeg:

Input #0, avisynth, from 'C:\Users\D\Downloads\test_temp\test.avs':
  Duration: 00:23:42.09, start: 0.000000, bitrate: 0 kb/s
    Stream #0:0: Video: rawvideo (Y3[11][10] / 0xA0B3359), yuv420p10le, 1920x1080, 23.98 fps, 23.98 tbr, 23.98 tbn, 23.98 tbc

avs2pipemod:

C:\Users\David>C:\Users\D\Downloads\StaxRip-x64-1.8.2.0-test\Apps\avs2pipemod\avs2pipemod64.exe -y4mp C:\Users\D\Downloads\test_temp\test.avs | C:\Users\D\Downloads\StaxRip-x64-1.8.2.0-test\Apps\x264\x264-10b.exe - --demuxer y4m -o tff.mkv
avs2pipemod[info]: writing 34096 frames of 24000/1001 fps, 1920x1080,
                   sar 0:0, YUV-420-planar-10bit progressive video.
y4m [info]: 1920x1080p 0:0 @ 24000/1001 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x264 [info]: profile High 10, level 4.0, 4:2:0 10-bit

see, no issue with ffms2 with 10 bit

If I use LSmash and put "format=YUV420P10" then I get a double width (double the horizontal resolution has seen in Starxrip)
then I use convertfromdoublewidth(10) (after that the resolution is back to normal)
then ... If I feed the avs directly in x264 same error BUT still work in **ffmpeg and avs2pipemod**

**Comment by Revan654** [comment]
ffms is the issue like I said. Since YUV420P10 does encode with x264 just fine at my end. If FFMS is creating issues switch to another filter, if your dead set on ffms you could inject the ffms helper and see if it helps you at your end.

https://i.imgur.com/XVPvBxU.jpg
https://i.imgur.com/ULjxlJm.jpg

ffms is uses FFMPEG, since when it uses FFMPEG it gains additional resources.

**Comment by Funodav** [comment]
I look at your Screenshots and your resolution isn't normal : 2560x720 instead of 1280x720 that's because you didn't use convertfromdoublewidth(10) witch convert in the depth you put in the brackets, Whitout that the picture looks like green "garbage". (and an 8 bit one ;)).

**Comment by Revan654** [comment]
It's not 720p content, the Resolution is correct on the screenshot. The Picture is perfectly fine.

**Comment by Revan654** [comment]
Since this is not any issue related to StaxRip but an issue related to the Source Filters. Going to mark this post as Closed.
