### ISSUE TITLE
ffmpeg - x265 > Decoder > Nvidia // Hardware Decoding fails to initialize

### ISSUE THREAD

**Issue by Rick-N-Thailand** [Revan654/staxrip#90]
Hi,

Been experimenting with Nvidia Hardware Decoding with ffmpeg.  I receive an error with the current script used in the profile.  I am unable to edit the script to apply the workaround that seems to be working.

Current Template (Hardware decode to x265 encode using ffmpeg):
`%\Apps\Encoders\ffmpeg\ffmpeg.exe" -hwaccel cuvid -i  -c:v libx265 -an -y -hide_banner _out.mkv_out.mkv`

use of "cuvid" is causing this error:
>--decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
 >--Failed setup for format cuda: hwaccel initialisation returned error.

Possible solution that worked for me on a GTX 1080ti(pascal):
Change: CUVID to NVDEC
`%\Apps\Encoders\ffmpeg\ffmpeg.exe" -hwaccel nvdec -i  -c:v libx265 -an -y -hide_banner _out.mkv_out.mkv`

If this is not a complete solution, can we please have another decoder choice utilizing NVDEC?

If I could adjust the scripts that are hardwired into Staxrip, I can determine the best solution. 
 I am after an increased frame rate because I don't fully utilize my gpu.  Seems to be two methods for hardware decoding on Nvidia using ffmpeg:  [](https://trac.ffmpeg.org/wiki/HWAccelIntro)

**Comment by mofortin** [comment]
You could use the `Custom:` text box and write `-hwaccel nvdec` in it. The latest command line argument should override the first if it exists.

**Comment by Rick-N-Thailand** [comment]
Thanks for the comment.  I tried to enter in the custom box.  However, it puts the code at the end of the 1st half of the script (decode) just before the (encode) section.  I also tried to enter the most of the code in correct order, however this didn't work too.  

My goal is to increase my processing speed since it appears to decode gpu encode cpu at the same time.  However, from my reading, gpu decode should be similar to cpu decode in quality making it an option.  I have a AMD 1950x which is quite powerful in it's own sense.  I am not sure how effective this will be without it working inline.  Seems to give about 15-20% speed increase running on it's own outside staxrip.  However this is not the full process with audio, filters, etc...

**Comment by mofortin** [comment]
Indeed, CPU and GPU decoding should be pretty similar, in quality and in speed, since decoding isn't that demanding. So using HW decoding over SW decoding shouldn't give you that much of a speed increase.

**Comment by Revan654** [comment]
> 
> 
> Thanks for the comment. I tried to enter in the custom box. However, it puts the code at the end of the 1st half of the script (decode) just before the (encode) section. I also tried to enter the most of the code in correct order, however this didn't work too.
> 
> My goal is to increase my processing speed since it appears to decode gpu encode cpu at the same time. However, from my reading, gpu decode should be similar to cpu decode in quality making it an option. I have a AMD 1950x which is quite powerful in it's own sense. I am not sure how effective this will be without it working inline. Seems to give about 15-20% speed increase running on it's own outside staxrip. However this is not the full process with audio, filters, etc...
> 
> When entering in custom textbox:
> `%\Apps\Encoders\ffmpeg\ffmpeg.exe" -hwaccel cuvid -i -c:v libx265 -hwaccel nvdec -an -y -hide_banner _out.mkv_out.mkv`
> 
> If I do not select NVIDIA Decoder and enter in custom textbox:
> `%\Apps\Encoders\ffmpeg\ffmpeg.exe" -i -c:v libx265 -hwaccel nvdec -an -y -hide_banner _out.mkv_out.mkv`

You will not get much out of hardware decoder vs software. The GPU will always hit bottlenecking since it has to wait for the CPU to finish first before it can do anything else. You may only get a small speed bust at the start but as it encodes that gain will be completely wiped out. If you stack filters and such there is no point in using it at all.

AMD had horrible bottlenecking as it passed data through it's channels. It was Ryzen line that was affected. I know the first gen never got fixed, not sure if it was addressed as newer chips were released.

FYI, It's the GHZ that plays the biggest role with encoding with the CPU. Many Programs have capped the amount of cores you can use (aka Handbrake is one of them). It only allows you to use six. Not sure if this is a limitation of handbrake or ffmpeg.

I tested this awhile back with the code added to StaxRip, but it didn't merit adding it to final release.

**Comment by Rick-N-Thailand** [comment]
Hi,  Thanks for the Message and Guidance

I was suspecting speed won't be too much faster but trying to streamline my process.

In general, h264 and below content runs my CPU across all threads at about 30% (I run two instances).  h265 content runs my cpu 55-70%.  My setup is running high 23,000 low 24,000 passmark scores tweaked a bit to run high but stable.  My h264 to h265 is depending on the source is about 1.1x to 1.5x encode speed.

I ran the same H264 video with ffmpeg/DXVA2 hardware decoding >to>X265 encoding with the same parameters gaining about 1fps... very nominal.  I agree not worth the effort.  In addition, running this way doesn't allow me to use the knlmeans opencl filter and hevc-aq(really like this new feature for size saving).

From my research, the 1950x, 2950x are best for processing at the moment with 16 cores... Beyond 16 cores the Windows Scheduler cannot manage the AMD CPU well for video encode tasks because they in a sense are acting like multi-cpu on one die.  Level1Tech's youtube channel went way into detail on the matter. 

Handbrake in general now utilizes all my cores and scales well on my 16 core 1950x close to 90% but don't like the audio processing.  I want to be able to normalize the sound level when processing.  I do like the foreign sub scan and burnin process ;)

From ffmpeg, they say CUVID is the older depreciated call and NVDEC is the preferred newer call to utilize Nvidia Hardware Decoding. [](https://trac.ffmpeg.org/wiki/HWAccelIntro)

> NVDEC/CUVID
> NVDEC offers decoders for H.264, HEVC, MJPEG, MPEG-1/2/4, VP8/VP9, VC-1. Codec support varies by hardware (see the ​GPU compatibility table).
> 
> Note that FFmpeg offers both NVDEC and CUVID hwaccels. They differ in how frames are decoded and forwarded in memory.
> 
> The full set of codecs being available only on Pascal hardware, which adds VP9 and 10 bit support. The note about missing ffnvcodec from NVENC applies for NVDEC as well.
> 
> Sample decode using NVDEC:
> 
> `ffmpeg -hwaccel nvdec input output`
> Sample decode using CUVID:
> 
> `./ffmpeg-git -hwaccel cuvid -c:v h264_cuvid -i input output`
> Full hardware transcode with CUVID and NVENC:
> 
> `ffmpeg -hwaccel cuvid -c:v h264_cuvid -i input -c:v h264_nvenc -preset slow output`
> If ffmpeg was compiled with support for libnpp, it can be used to insert a GPU based scaler into the chain:
> 
> `ffmpeg -hwaccel_device 0 -hwaccel cuvid -i input -vf scale_npp=-1:720 -c:v h264_nvenc -preset slow output.mkv`
> The -hwaccel_device option can be used to specify the GPU to be used by the hwaccel in ffmpeg.

From ffmpeg, the CUVID call in staxrip is missing information to complete the script.  It appears if using NVDEC the script matches in Staxrip.

Thanks again

**Comment by Rick-N-Thailand** [comment]
Hi Revan,

Can we have the embedded script for (ffmpeg>encoder>"NVIDIA") changed from CUVID to NVDEC so the script does not error out?  Thanks...

**Comment by mofortin** [comment]
https://github.com/Revan654/staxrip/pull/92 should do the trick... I kept the old option as well for compatibility purpose i guess

**Comment by Revan654** [comment]
> 
> 
> #92 should do the trick... I kept the old option as well for compatibility purpose i guess

That's Only a Fragment, Other things need to be changed as well, Which then would require making changes to encoding files and other misc files for the new option.

**Comment by lealpa** [comment]
Hello!

I'm getting similar error messages when using this command:

**ffmpeg -re -hwaccel cuvid -hwaccel_output_format cuda -extra_hw_frames 10 -i rtmp://xxxxxxxxx -map 0 -c:v h264_nvenc -b:v 2M -maxrate 2M -qmin 34 -qmax 51 -g 60 -bf 3 -b_ref_mode middle -bufsize 1M -c:a aac -ar 44100 -ac 1 -flush_packets 0 -f mpegts "udp:xxx.xxx.xxx.xxxx:xxxx"**

[h264 @ 0x5641628791c0] decoder->cvdl->cuvidCreateDecoder(&decoder->decoder, params) failed -> CUDA_ERROR_INVALID_VALUE: invalid argument
[h264 @ 0x5641628791c0] Using more than 32 (37) decode surfaces might cause nvdec to fail.
[h264 @ 0x5641628791c0] Try lowering the amount of threads. Using 16 right now.
[h264 @ 0x5641628791c0] Failed setup for format cuda: hwaccel initialisation returned error.

Please, give me some advice

Cheers!

**Comment by pranaydeep01** [comment]
@lealpa I am also facing exactly the same error only for a a particular video. Did you find anything ?

**Comment by lealpa** [comment]
> @lealpa I am also facing exactly the same error only for a a particular video. Did you find anything ?

Not it all , buddy, I'm still looking for a solution. I'll let you know when - or if - I find it!

**Comment by eaglerainbow** [comment]
@lealpa @pranaydeep01  please be aware of https://forums.developer.nvidia.com/t/nvdec-fails-on-file-requires-29-threads-surfaces-thus-fails-on-3-threads/240827
