### ISSUE TITLE
Script error 1114 with dfttest.dll when using QTGMC

### ISSUE THREAD

**Issue by xunkar** [Revan654/staxrip#95]
![image](https://user-images.githubusercontent.com/329857/56850848-59472380-6908-11e9-9a08-d65ee0a1cdda.png)

When turning QTGMC on, DFTTest returns an error 1114

**Comment by mofortin** [comment]
Works fine on version 2.0.0. 
-->http://avisynth.nl/index.php/Dfttest
Dfftest requires FFTW dll. Are you sure you have it installed ?

**Comment by Revan654** [comment]
Your CPU doesn't seem to support AVX2, You have to extract the correct version to the folder and replace the existing one(the other versions are inside of a zip file that's inside the folder).

All current dll's that support CPU vectoring is set to AVX2.

**Comment by xunkar** [comment]
Yes my CPU only supports AVX, switching the DLL worked thank you.
