### ISSUE TITLE
ffmsindex not detecting track 0 video causing d2v to not be found

### ISSUE THREAD

**Issue by imPRAGMA** [Revan654/staxrip#96]
**Describe the bug or Issue**
Opening a mkv of a MPG codec video wont discover track 0 for use with mkvextract, resulting in it not extracting the video for some odd reason. This Leads to MPEG2Source being unusable as it cant find the .d2v as it cant be created as the .mpg wasnt extracted.

**Step To Reproduce the Problem**

1. Set MPEG2Source
2. Load a mkv file (Seemingly only specific mkvs have issues)
3. It will run it but fails

```
------------------ Demux MKV using mkvextract 26.0.0 ------------------

C:\Users\x\Downloads\1.9.0.0.x64\Apps\MKVToolNix\mkvextract.exe "D:\Video\THE_LITTLES 2\title_t00 (1)-021.mkv" tracks 1:"D:\Video\THE_LITTLES 2\title_t00 (1)-021_temp\title_t00 (1)-021 ID1 3ms English.mka" --ui-language en
```

As you can see here, the issue is fairly strange

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1803
- Version: 1.9.0.0
- FrameServer Being Used: AviSynth
- Version of External Application / Filter Being Used: N/A?
- List of Filters Being Used: MPEG2Source

**Comment by Revan654** [comment]
Nothing I can do about ffindex, Since that software hasn't been updated in ages. You can also try new or older versions of MediaInfo since it's know to create problems with certain formats.

Try updating your Build, Since 1.9 is old.
