### ISSUE TITLE
Error opening MKV. Demux error

### ISSUE THREAD

**Issue by IceT75** [Revan654/staxrip#97]
**Notes Before Posting**
- Only Open an issue if it's tied to Staxrip, If issues is tied to external program or filter. Head to Resp page for that project and open an issue there. 
- Beta Releases are Not Covered, Beta Are Pre-Releases and Could Contain Bugs. This is the Risk Your Willing to Take When using Beta releases. Beta Concerns should be posted in the forums.
- If you Require Help with one of the FrameServers, Programs or Scripting Post in the Forums, Rather then opening a ticket here.
  Link: https://forum.doom9.org/showthread.php?t=175845
- Check your CPU Specs as Well. Many newer Filters are AVX2 Enabled with no AVX1 support(This is espeically True on VapourSynth side. Which will crash the software if your CPU doesn't support it.
- Lastly, Only Files that are Released with StaxRip are fully supported, This is done to make debugging easier. Also since all filters have been tested before release. Newer versions can have changes which have not been added to StaxRip yet.

**Describe the bug or Issue**

**Add The Proper Label**

**Step To Reproduce the Problem**

3. Using '...' Encoder
4. 'Avisynth or VapourSynth' Being Used 
6. Filter(s) x is being Used.
7. Any Major External Files tied to the Error.
8. Post Both your Log file & AVS/VS Script.
9. It it's Tied to Hardware Encoder Post your Hardware Specs along with the Following.

**Screenshots**
If possible, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Build 1803]
- Version [e.g. 1.9]
- FrameServer Being Used [e.g. Avisynth]
- Version of External Application / Filter Being Used [e.g. 2.9+10]
- List of Filters Being Used [e.g. QTGMC]
- Post your Logs, There Tell contain Allot of Information that Could Help.
- The More Information Posted, The Easier it will be to Debug.

**Additional context**
Add any other Information or additional context that can be Helpful.

**Please be Clear and as Detailed as Possible**

**Any Issues left unattended to for Length of Time will automatically be Closed Due and or Locked to inactivity**
This Is The LOG:

------------------------- System Environment --------------------------

StaxRip    : 2.0.0.1
Windows    : Windows 7 Ultimate
Language   : Italian (Italy)
CPU        : Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
GPU        : AMD Radeon R9 200 Series
Resolution : 1280 x 1024
DPI        : 96

------------------------ MediaInfo Source File ------------------------

F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4

General
ID                       : 1 (0x1)
Complete name            : F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4
Format                   : MPEG-TS
File size                : 3.24 GiB
Duration                 : 1 h 29 min
Overall bit rate mode    : Variable
Overall bit rate         : 5 211 kb/s
FileExtension_Invalid    : ts m2t m2s m4t m4s tmf ts tp trp ty

Video
ID                       : 258 (0x102)
Menu ID                  : 1 (0x1)
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4
Format settings          : CABAC / 4 Ref Frames
Format, CABAC            : Yes
Format, ReFrames         : 4 frames
Codec ID                 : 27
Duration                 : 1 h 29 min
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate               : 25.000 FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive
Writing library          : x264 core 148
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709

Audio
ID                       : 257 (0x101)
Menu ID                  : 1 (0x1)
Format                   : AAC LC
Format/Info              : Advanced Audio Codec Low Complexity
Format version           : Version 4
Muxing mode              : ADTS
Codec ID                 : 15-2
Duration                 : 1 h 29 min
Bit rate mode            : Variable
Channel(s)               : 2 channels
Channel layout           : L R
Sampling rate            : 48.0 kHz
Frame rate               : 46.875 FPS (1024 SPF)
Compression mode         : Lossy
Delay relative to video  : -40 ms

----------- Error Demux audio using MP4Box 0.7.2-DEV-rev1009 -----------

Demux audio using MP4Box 0.7.2-DEV-rev1009 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Funzione non corretta.

-------------- Demux audio using MP4Box 0.7.2-DEV-rev1009 --------------

"C:\Program Files (x86)\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -single 257 -out "F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007)_temp\Una Bionda A New York (2007) ID1 -40ms.mka" "F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4"

[33m[iso file] Unknown box type ....
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type .{..
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type C..f
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type Lp.7
[0m[31m[iso file] Incomplete box UNKN
[0m[31m[iso file] Incomplete file while reading for dump - aborting parsing
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type .{..
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type C..f
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type Lp.7
[0mTruncated file - missing 3210264230 bytes
Error opening file F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4: IsoMedia File is truncated

-------------- Demux audio using MP4Box 0.7.2-DEV-rev1009 --------------

"C:\Program Files (x86)\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -single 257 -out "F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007)_temp\Una Bionda A New York (2007) ID1 -40ms.mka" "F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4"

[33m[iso file] Unknown box type ....
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type .{..
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type C..f
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type Lp.7
[0m[31m[iso file] Incomplete box UNKN
[0m[31m[iso file] Incomplete file while reading for dump - aborting parsing
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type .{..
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type C..f
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type Lp.7
[0mTruncated file - missing 3210264230 bytes
Error opening file F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4: IsoMedia File is truncated

Start:    20:32:51
End:      20:32:52
Duration: 00:00:01

------------------------------ Exception ------------------------------

StaxRip.ErrorAbortException: Demux audio using MP4Box 0.7.2-DEV-rev1009 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Funzione non corretta.

-------------- Demux audio using MP4Box 0.7.2-DEV-rev1009 --------------

"C:\Program Files (x86)\StaxRip\Apps\Support\MP4Box\MP4Box.exe" -single 257 -out "F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007)_temp\Una Bionda A New York (2007) ID1 -40ms.mka" "F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4"

[33m[iso file] Unknown box type ....
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type .{..
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type C..f
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type Lp.7
[0m[31m[iso file] Incomplete box UNKN
[0m[31m[iso file] Incomplete file while reading for dump - aborting parsing
[0m[33m[iso file] Unknown box type ....
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type .{..
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type C..f
[0m[33m[iso file] Unknown box UNKN (0x554E4B4E) with payload larger than 1 MBytes, ignoring
[0m[33m[iso file] Unknown box type Lp.7
[0mTruncated file - missing 3210264230 bytes
Error opening file F:\Da Convertire in MKV\OK\Da Comprimere\Una Bionda A New York (2007).mp4: IsoMedia File is truncated

   in StaxRip.Proc.Start()
   in StaxRip.MP4BoxDemuxer.Demux(String sourcefile, AudioStream stream, AudioProfile ap, Project proj)
   in StaxRip.MP4BoxDemuxer.Run(Project proj)
   in StaxRip.MainForm.Demux()
   in StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding)

**Comment by Revan654** [comment]
MP4Box can't reach � characters, Nothing I can do about that since I don't have control over that piece of software.

Also make sure your command window is set to format that can read the output format.
