### ISSUE TITLE
can we have another build please like 2.0.0.2?

### ISSUE THREAD

**Issue by pwacooijmans** [Revan654/staxrip#99]
Is it possible to make a new build yet that can be downloaded.
Or do you have a link where I can download the changes to staxrip.

Just asking since there have been 11+ commits and I am interested in them as well.

Many Thanks,

Pieter Cooijmans

**Comment by iAM261917** [comment]
See Pipeline: https://github.com/Revan654/staxrip#pipeline
And go to Artifacts: https://ci.appveyor.com/project/Revan654/staxrip/build/artifacts
(although I'm not sure if I was right or not.)

**Comment by pwacooijmans** [comment]
I kinda ment a new executable version for windows 10 instead of having to
compile it myself. This is because I don't know how to compile staxrip.

Kind regards,

Pieter Cooijmans

Op zo 26 mei 2019 om 08:40 schreef iAM261917 <notifications@github.com>:

**Comment by mofortin** [comment]
I do think the ZIP file from the archives ( link from iAM261917 ) is indeed the compiled version with the executable.. The only thing missing in that zip are the external libraries... So basically you should be able to just extract the ZIP into your current installation folder

**Comment by Revan654** [comment]
There have been allot of changes on how StaxRip is Developed now. All the Releases Can Be Found on The Official Project Page: https://github.com/staxrip/staxrip or The Pipeline.

It contains work from both Stax and myself.
